### PR TITLE
Fix full screen to support more browsers

### LINKED ISSUE #851: Fullscreen doesn't work on Safari
## Description

Full screen doesn't work in Safari browser. Apparently Safari doesn't support the `requestFullscreen` API yet.

## What's the behavior that you expect?

Full screen works in Safari

## What's happening instead?

Clicking fullscreen generates this error in the JS console:

```text
this.shadowRoot
.querySelector(".screen-wrapper")
.requestFullscreen is not a function.
```

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Safari 15
2. Click on View > Full Screen

## Root cause

Safari doesn't support the `requestFullscreen` API:

https://caniuse.com/fullscreen

If looks like the fix is to do something like this:

```javascript
let requestFullscreen = element.requestFullscreen
if (!requestFullscreen) {
  requestFullscreen = element.webkitRequestFullscreen
}
requestFullscreen();
```

### PR DESCRIPTION
**Pull request by djclueless**
Resolves #851

This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/874)

### CODE REVIEW

**Comment by djclueless** [comment]
Addresses Issue #851

**Review by mtlynch — CHANGES_REQUESTED** [review]
Thanks for contributing this. Good to hear from you again!

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/874#-:-Ms1_xfz-5tR3kQtkCRU:b-k22d7f)* status: 0 of 1 LGTMs obtained

___
*[app/templates/custom-elements/remote-screen.html, line 220 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/874#-Ms1_oTD8NFzuiwVdM0t:-Ms1_oTD8NFzuiwVdM0u:bwb6rkn) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/4044922a0d19ffefaf47b9a454dac7c4a3e522e7/app/templates/custom-elements/remote-screen.html#L220)):*
> ```HTML
>         attributeChangedCallback(name, oldValue, newValue) {
>           if (name === "fullscreen" && newValue === "true") {
>             let e = this.shadowRoot.querySelector(".screen-wrapper");
> ```

Can we change this `const screenWrapper = ...`? to make it more expressive?

**Comment by djclueless** [comment]
No problem, fixed.   Glad to be back :)

**Review by mtlynch — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/874#-:-Ms222OH72kwYY7QvjRo:bg7igkv)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
