### PR TITLE
Create bundle using local `ansible-role` directory.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1174

This PR bundles the local `ansible-role` directory into the TinyPilot bundle file and corrects the documentation that previously referenced the [`ansible-role-tinypilot` repo](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/70321141a8f90589962f1ae4069002afad355b7b).

### Notes

* After merging this PR, we can safely archive the [`ansible-role-tinypilot` repo](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/70321141a8f90589962f1ae4069002afad355b7b) (as readonly)
* I have successfully tested the [build bundle](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2964/workflows/e69ad101-634a-48b1-a345-6c4bced166e5/jobs/13760/artifacts) on a device running Raspberry Pi OS Lite Buster

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1286">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1286)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1286)



<hr />

In: **bundler/create-bundle**:
Sure, then I also changed the following comment for consistency with the action being performed (https://github.com/tiny-pilot/tinypilot/pull/1286/commits/ed1da5d2a8fea3227163f22e2fb80b393a9d73d8).

**Comment by jdeanwallace** [comment]
@mtlynch - The TinyPilot Community bundle is [now using the consolidated `ansible-role`](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2987/workflows/035348ce-0439-4a74-b68f-aad3de62065e/jobs/13998?invite=true#step-104-103). Can you please archive the [`ansible-role-tinypilot` repo](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/70321141a8f90589962f1ae4069002afad355b7b) (i.e., set it as readonly)?

**Comment by mtlynch** [comment]
@jdeanwallace - Sure, done. Let me know when Pro is ready for the same treatment.

**Comment by jdeanwallace** [comment]
@mtlynch - Thanks, yes [Pro is ready to be archived](https://github.com/tiny-pilot/tinypilot-pro/pull/746#issuecomment-1416145152) too.

**Pull request merged**
