### PR TITLE
Add logic for building TinyPilot install bundles

### PR DESCRIPTION
**Pull request by mtlynch**
This merges the https://github.com/tiny-pilot/tinypilot-bundler repo into this repo, per discussion in https://github.com/tiny-pilot/tinypilot-bundler/issues/19.

Changes:

* Changed paths to reflect the placement within the new repo.
* Deleted the README
* Deleted the `dev-scripts` folder as the same scripts already existed in this repo.
* Deleted the `check_bash` and `check_whitespace` CircleCI jobs as they already existed in this repo.

After we merge this in, the tinypilot-bundler repo will become obsolete and we'll mark it as read-only.

Fixes https://github.com/tiny-pilot/tinypilot-bundler/issues/19

This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/986)

### CODE REVIEW

**Review by jotaen4tinypilot — APPROVED** [review]
:lgtm: 

Shall I move over all the issues from [the mega ticket](https://github.com/tiny-pilot/tinypilot-pro/issues/445) to either the Community or Pro repo, or shall we keep the bundler repository open until the project is complete? In the latter case, we could delete all files to avoid confusion, an leave a README with a brief note.

I’ve also [added a note for us to write up a guide for local development](https://github.com/tiny-pilot/tinypilot-bundler/issues/4), but I think this can wait until we reached a more stable state.

Shall we carry over the [`.gitignore` file](https://github.com/tiny-pilot/tinypilot-bundler/blob/master/.gitignore)? (Either merge it with the root one, or copy it as is to `/bundler`.) Otherwise, when building locally, the ansible repos and the build output pop up in git.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/986#-:-N4gESJT0RG8pbpvIH8y:b46ivzf)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by mtlynch** [comment]
>Shall I move over all the issues from the mega ticket to either the Community or Pro repo, or shall we keep the bundler repository open until the project is complete? In the latter case, we could delete all files to avoid confusion, and leave a README with a brief note.

Oh, right. Yeah, let's move over the issues. I don't think Github will let you transfer an issue from a private repo to a public repo, so let's move all the issues to Pro first, and then make tinypilot-bundler public to transfer the rest to Community. There wasn't anything secret in the tinypilot-bundler repo.

>Shall we carry over the .gitignore file? (Either merge it with the root one, or copy it as is to /bundler.) Otherwise, when building locally, the ansible repos and the build output pop up in git.

Ah, right. I missed this in the copy. Fixed.

**Comment by jotaen4tinypilot** [comment]
> Let's move all the issues to Pro first, and then make tinypilot-bundler public to transfer the rest to Community. There wasn't anything secret in the tinypilot-bundler repo.

I’m not sure I follow: if we moved all issues to Pro, then there wouldn’t be any issues left to transfer to Community? Or do you mean the open ones to Pro and the closed ones to Community?

([You are right that it’s not possible to transfer from private to public](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository#:~:text=Note%3A%20You%20can%20only%20transfer%20issues%20between%20repositories%20owned%20by%20the%20same%20user%20or%20organization%20account.%20A%20private%20repository%20issue%20cannot%20be%20transferred%20to%20a%20public%20repository.).)

**Comment by jotaen4tinypilot** [comment]
Ah right, thanks! I’ll take care of it.

**Comment by jotaen4tinypilot** [comment]
@mtlynch I have transferred two issues to Pro, the remainder can live in Community. Could you make the bundler repo public please? (I don’t have access to the repo settings.)

**Comment by mtlynch** [comment]
@jotaen4tinypilot - Sure, done.

**Comment by jotaen4tinypilot** [comment]
@mtlynch we can archive the bundler repo now.

**Comment by mtlynch** [comment]
@jotaen4tinypilot - Cool, thanks for moving everything! I've archived the bundler repo.

**Pull request merged**
