### PR TITLE
Build bundle `ansible-role-tinypilot` version.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Dependent on https://github.com/tiny-pilot/tinypilot/pull/1075
Resolves https://github.com/tiny-pilot/tinypilot/issues/1071

This PR builds the bundle file using the `update-overhaul` branch of `ansible-role-tinypilot`.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1076">Review on CodeApprove</a>

### CODE REVIEW

**Review by jotaen4tinypilot — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1076)


✔️ Approved

<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by jdeanwallace** [comment]
I'm going to wait for https://github.com/tiny-pilot/ansible-role-tinypilot/pull/205 to be merged in order to get those changes into the bundle file.

**Comment by mtlynch** [comment]
@jdeanwallace - We've got a circular dependency in that case.

If https://github.com/tiny-pilot/ansible-role-tinypilot/pull/205 merges in, then users start hitting the new update flow (tinypilot:master points to ansible-role-tinypilot:master, which will change references to get-tinypilot.sh).

Do you want me to change https://github.com/tiny-pilot/ansible-role-tinypilot/pull/205 to go into an `update-overhaul` branch?

**Comment by jdeanwallace** [comment]
> Do you want me to change https://github.com/tiny-pilot/ansible-role-tinypilot/pull/205 to go into an update-overhaul branch?

@mtlynch - Yes please. I also [made a comment on that PR](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/205#issuecomment-1198039778), but you might have missed it.

**Pull request merged**
