### PR TITLE
Resolve tinypilot home dir independent from $HOME

### PR DESCRIPTION
**Pull request by jotaen4tinypilot**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1571.

There are several places in the app where we rely on the `~` path shortcut, or the `$HOME` environment variable respectively. (For example when [processing the `settings.yml` file](https://github.com/tiny-pilot/tinypilot/blob/master/app/update/settings.py#L21).) However, there are scenarios where the app (or parts of it) are run under a different user, e.g. `root`, or with `sudo`, in which case `~` would erroneously resolve to `/root` instead of `/home/tinypilot`.

This PR makes sure that the app always uses `/home/tinypilot` for accessing TinyPilot-specific objects, independent of what the `$HOME` environment variable contains. TinyPilot-specific objects are:

- `settings.yml`
- `logs/**` (i.e., update result logs)
- `.flask-secret-key`
- `tinypilot.db`
- `app_settings.cfg` (no change needed, as [this is already referenced in an absolute manner](https://github.com/tiny-pilot/tinypilot/blob/504e7f113d21f90824acf229240167cafed39b17/debian-pkg/debian/tinypilot.service#L12))

I suggest that we don’t just hard-code the `/home/tinypilot` path as is, because that would make local development more inconvenient – you always would need to initialize and switch to a `tinypilot` user before being able to start developing. Therefore, I introduced a new environment variable (`TINYPILOT_HOME_DIR`), that lets us overrride the `/home/tinypilot` default. Unfortunately, we cannot put this variable into [`dev_app_settings.cfg`](https://github.com/tiny-pilot/tinypilot/blob/504e7f113d21f90824acf229240167cafed39b17/dev_app_settings.cfg), since the app config can only be read during a Flask request execution context, but not at initialization time (at least not in a “clean” way). To me, the `env.abs_path_in_home_dir` helper function (as proposed here) wouldn’t be too bad either, though.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1572">Review on CodeApprove</a>

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)



<hr />

In: **app/env.py**:

```
> Line 25
    return str(pathlib.Path(_TINYPILOT_HOME_DIR).joinpath(relative_path))
```
Can we harden this against [path traversal](https://owasp.org/www-community/attacks/Path_Traversal) attacks? In other words, if the caller passes `../../etc/shadow`, we should throw an exception.

It's not an issue now, and it probably won't be, but I'd prefer to just have defense in depth.

Can we verify that the final absolute path is a path *within* the `TINYPILOT_HOME_DIR` directory?


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)



<hr />

In: **app/env.py**:
Cool, thanks! Those tests look good.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **app/env.py**:

```
> Line 34
    target = _TINYPILOT_HOME_PATH.joinpath(relative_path).resolve()
```
The tests are failing on my dev machine, and it looks like another macOS specific issue. My resolved target directory ends up looking like this:
```
target: /System/Volumes/Data/home/tinypilot/tinypilot.db
target: /System/Volumes/Data/home/tinypilot/tinypilot.db
target: /System/Volumes/Data/home/tinypilot/.flask-secret-key
target: /System/Volumes/Data/home/tinypilot/logs
target: /System/Volumes/Data/home/tinypilot/logs
target: /System/Volumes/Data/home/tinypilot/tinypilot.db
target: /System/Volumes/Data/home/tinypilot/logs
```

So it seems like `/home/tinypilot` resolves to `/System/Volumes/Data/home/tinypilot` on macOS 😬


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1572">Approved on CodeApprove</a>
✔️ Approved

<hr />

In: **app/env.py**:

```
> Line 34
    target = _TINYPILOT_HOME_PATH.joinpath(relative_path).resolve()
```
Well I run the tests straight from macOS and not in a VM, so the tests would fail for me going forward. I can however rely more on CircleCI to run tests or run tests individually if I'm adding more tests. I know this is more of a "me issue" unfortunately. I can't think of easy way around it though.


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)



<hr />

In: **app/env.py**:

```
> Line 34
    target = _TINYPILOT_HOME_PATH.joinpath(relative_path).resolve()
```
Could we add `unittest.skipIf(isMacOs())` to the failing tests?


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1572)



<hr />

In: **app/env.py**:

```
> Line 34
    target = _TINYPILOT_HOME_PATH.joinpath(relative_path).resolve()
```
Right, sorry, just pseudocode.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Pull request merged**
