### PR TITLE
Add incompatible hardware check to installation script

### LINKED ISSUE #1221: Block install if we detect incompatible hardware
Some users install the TinyPilot software on incompatible hardware like Raspberry Pi 3. This can cause some issues with support requests if we try and debug an issue that stems from incompatible hardware (USB OTG etc.).

It would be good to stop the install process early on and alert the user that TinyPilot isn't compatible with their device. Perhaps with a prompt to continue if they're working on [installing TinyPilot on alternate OSes or hardware](https://github.com/tiny-pilot/tinypilot/discussions/755)?

### PR DESCRIPTION
**Pull request by cghague**
Resolves #1221 by adding a step to check for incompatible hardware to the installation script.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1230">Review on CodeApprove</a>

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)



<hr />

In: **get-tinypilot.sh**:

```
> Line 57
if ! grep -q "4 Model B\|Zero 2 W" /proc/cpuinfo ; then
```
We need to make this an blocklist rather than an allowlist otherwise it's going to create headaches for us during testing / CI.

Can we simplify to just erroring out if we detect we're on a Pi 3 (any variant)? That's the most common source of support requests. And then let's skip the override option because there's no reason to force install on a Pi 3.


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)



<hr />

In: **get-tinypilot.sh**:

```
> Line 57
if ! grep -q "4 Model B\|Zero 2 W" /proc/cpuinfo ; then
```
I've been looking into this and it seems that `/proc/cpuinfo` doesn't output the same results on a Raspberry Pi 3 - crucially, the "Model" line is omitted. We could potentially modify the test to use the "Revision" line instead and compare against the information on https://elinux.org/RPi_HardwareHistory. It's not the cleanest solution and I also believe that list is incomplete as it doesn't contain a matching entry for my TinyPilot Voyager 2.

It looks like `/proc/device-tree/model` contains the same information on a Raspberry Pi 4 and I've found a single mention (on a Reddit thread) which suggests that it also works on the Raspberry Pi 3. I don't have a Raspberry Pi 3 to confirm this.

@mtlynch or @db39 - Do either of you have a Raspberry Pi 3 and if so can you please confirm the output of `cat /proc/device-tree/model`?


<hr />

👀 @mtlynch it's your turn please take a look

**Comment by mtlynch** [comment]
@db39 - Do you have one? If not, I can dig up one of mine.

**Comment by db39** [comment]
@mtlynch, unfortunately I don't have a Pi3. I do have a Pi2 if that would be any use here?

**Comment by mtlynch** [comment]
I thought I had a Pi 3 on hand, but it turned out to be a Pi 2.

I spun up a Pi 3 and Pi 4 on [Mythic Beasts](https://www.mythic-beasts.com/) (cloud-hosted Pis, pretty neat service), and here was the output I got:

## Pi 3 (Mythic Beasts)

```bash
root@rpi-buster-armhf:~# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 0000000045e43ff6
Model           : Raspberry Pi 3 Model B Rev 1.2
```

## Pi 4 (Mythic Beasts)

```bash
root@rpi-buster-armhf:~# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03114
Serial          : 10000000fc97d887
Model           : Raspberry Pi 4 Model B Rev 1.4
```

## Pi 4 (Michael's Home System)

```bash
pilot@tinypilot:~ $ cat /proc/cpuinfo 
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : b03112
Serial          : 10000000eb788e1b
Model           : Raspberry Pi 4 Model B Rev 1.2
```

**Comment by cghague** [comment]
Thanks both! It looks like the line we need is there despite what I'd seen online. I'll set up a simple test to check if "Raspberry Pi 3" is present as that should catch the various variants.

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)



<hr />

In: **get-tinypilot.sh**:
Resolved


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **get-tinypilot.sh**:

```
> Line 57
if grep -q "Raspberry Pi 3" /proc/cpuinfo ; then
```
I'd like to reduce the odds of us accidentally matching a string on a different line. Can we tighten the regex to make sure it's the `Model` line?

```
"^Model *: Raspberry Pi 3""
```


<hr />

👀 @cghague it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **Discussion**
Can we update the PR description to remove the reference to the environment variable?

<hr />

In: **get-tinypilot.sh**:
Thinking about this more, I realized we should make these changes in `bundler/bundle/install`.

`get-tinypilot.sh` just bootstraps the install process, so we want the minimal amount of logic there. `install` does the heavy lifting.

Also `install` is shared by both TinyPilot Community and TinyPilot Pro, whereas `get-tinypilot.sh` is Community only. Pro uses a [different script](https://github.com/tiny-pilot/gatekeeper/tree/cbc45e1dddb9d608067945c8d8e0fd025cda5de1/static).


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)



<hr />

In: **Discussion**
Resolved

<hr />

In: **get-tinypilot.sh**:
Resolved

<hr />

In: **get-tinypilot.sh**:
Resolved

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1230)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Comment by cghague** [comment]
@mtlynch - It looks like this was set to auto-approve before your latest comments. Can you confirm you're still happy for this to be merged?

**Pull request merged**
