### PR TITLE
Add scripts to manage static IP addresses

### LINKED ISSUE #1244: Add scripts for setting and unsetting a static IP address
In our [static IP address FAQ](https://tinypilotkvm.com/faq/static-ip), we include a convenience script for setting the static IP. The script is inaccessible to users who have TinyPilots without Internet access, so we should ship the script with TinyPilot software itself.

The scripts should be in [`debian-pkg/opt/tinypilot-privileged/scripts/`](https://github.com/tiny-pilot/tinypilot/tree/566c6dc825cfb85996c6c608016e1ff9ae43e62c/debian-pkg/opt/tinypilot-privileged/scripts). 

We should change the semantics of the scripts to take better advantage of the fact that they're already loaded on the device.

### `set-static-ip`

```bash
set-static-ip --router router_ip --ip static_ip [--dns dns_ip]

Sets a static local IP address for the TinyPilot device.

--router router_ip: The IP address of the local router.
--ip static_ip: The static IP address to assign to the TinyPilot device.
--dns dns_ip: (optional) The DNS server for TinyPilot to use to resolve domain names. To specify multiple servers, separate the IPs with spaces. If unspecified, defaults to the router's DNS, then Google (8.8.8.8), then Cloudflare (1.1.1.1).

Examples:

# Set static IP to 10.0.105 on a 10.0.0.x network.
set-static-ip \
  --router 10.0.0.1 \
  --ip 10.0.0.105

# Set static IP to 192.168.1.100 and specifies a Quad9 DNS server
set-static-ip \
  --router 192.168.1.1 \
  --ip 192.168.1.100 \
  --dns 9.9.9.9
```

### `unset-static-ip`

```bash
unset-static-ip

Reverts changes made by the set-static-ip script.
```

The scripts can either be bash scripts or Python scripts.

### PR DESCRIPTION
**Pull request by cghague**
Resolves #1244 by adding scripts to manage static IP addresses.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1256">Review on CodeApprove</a>

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)



Cool, this is great! Lots of improvements over the hosted version.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 6
set -e
```
Can we also `set -u` once we've finished parsing all the flags? Ditto in the unset script.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 14
  --router router_ip: The IP address of the local router.
```
Can we give examples for all the flags, like:

>The IP address of the local router (e.g., 10.0.0.1)

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 20
Multiple DNS servers can be provided. If unspecified, defaults to the router's
```
Can we group this with the --dns flag documentation above?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 21
DNS, then Google (8.8.8.8), then Cloudflare (1.1.1.1).
```
Can we give full examples that show how to use the different flags? (one using the minimum number of flags, one using all the flags)

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 25
# Use the same values as the previous script for compatibility.
```
I'd like to cut this. If a reader sees this and doesn't know about the hosted script, they won't understand this. But they don't really need to know because once this script exists, it will have to be compatible with previous runs of the script, so we'll know not to just switch the markers.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 27
readonly MARKER_START='# --- AUTOGENERATED BY TINYPILOT - START ---'
```
I'd like to avoid duplicating these in different files. Especially here where we have to keep them in-sync between set and unset scripts.

Can we put these in `../lib/markers.sh` so that we can share them across scripts? And then [`change-hostname`](https://github.com/tiny-pilot/tinypilot/blob/7d90d95c59e79fe83214f9c0c1af93fbecf3e519/debian-pkg/opt/tinypilot-privileged/scripts/change-hostname#L12) can share it too.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 44
        echo "Only one static IP address should be provided." >&2
```
Can we name the flag specifically?

(ditto for routers and interfaces)

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 83
if [[ -z "${IP_ADDRESS}" ]] || [[ -z "${ROUTERS}" ]] ; then
```
Can we print a more specific error message to stderr?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 106
  echo "Please remove the existing configuration and try again." >&2
```
Can we tell them the path to the config file so they know where they have to make the fix?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:

```
> Line 6
# set-static-ip script. It is intentionally excluded from the help text.
```
Let's keep things simple and document the flag normally in the usage output. We would only leave it undocumented if we wanted to avoid having to support it for users who want it for other reasons, but the cost of supporting this flag is so low and it's fairly unlikely that users will script against this flag and expect us to maintain it.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:

```
> Line 86
  echo "Unclosed marker section." >&2
```
Can we make this a bit more actionable so that we're guiding the user toward what they need to do to fix it?


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 6
set -e
```
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 141
  echo "Please remove the existing configuration and try again." >&2
```
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:
Resolved


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 2
# shellcheck disable=SC2034
```
I agree with the suppression but can we add a comment explaining why to save the reader from having to look up the shellcheck code?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 6
readonly MARKER_START='# --- AUTOGENERATED BY TINYPILOT - START ---'
```
Can we use these in `change-hostname` as well?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 62
        echo "Only one static IP address should be provided using --ip." >&2
```
Can we leave off the trailing period? I personally often copy/paste the flag from the command-line, so having a trailing period makes the copy a little tougher.

(ditto for other places where we have a period right after a flag)

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:

```
> Line 64
        echo "  set-static-ip --help" >&2
```
Can we refactor these two lines into a function so we don't have to duplicate them?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:

```
> Line 33
source "${SCRIPT_DIR}"/lib/markers.sh
```
Can we quote the full path? Your way works but our convention is to quote the full path if we need to quote part of it.


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 2
# shellcheck disable=SC2034
```
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 8
readonly MARKER_START='# --- AUTOGENERATED BY TINYPILOT - START ---'
```
Resolved. I thought this was out of scope and so was going to raise a separate change for it.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/set-static-ip**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/unset-static-ip**:
Resolved


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/change-hostname**:

```
> Line 13
source "${SCRIPT_DIR}/lib/markers.sh"
```
Can we use `.` instead of `source`? I think `source` is more readable, but `.` is more consistent with the rest of the repo.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 4
# disable the unused variable check for this file.
```
Our convention is to either put the comment [on the same line](https://github.com/tiny-pilot/tinypilot/blob/289b85ab160117f688bfe00db38c817b610cf079/bundler/bundle/install#L112) or [before the shellcheck directive](https://github.com/tiny-pilot/tinypilot/blob/9c45a76b8ce72e5d1494ac6c268022cb4c516e15/dev-scripts/install-from-source#L38L41).


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/change-hostname**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/lib/markers.sh**:

```
> Line 3
# disable the unused variable check for this file.
```
Resolved

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1256)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
