### PR TITLE
Add upgrade paths to Pro

### LINKED ISSUE #766: Add upgrade paths to Pro
We should experiment with two upgrade paths to TinyPilot Pro:

System > Upgrade -> just brings user to https://tinypilotkvm.com/product/tinypilot-pro?ref=tinypilot-app

System > Virtual Media -> Shows a dialog saying that this feature is available in TinyPilot Pro with a button to upgrade, which points to https://tinypilotkvm.com/product/tinypilot-pro?ref=tinypilot-app

### PR DESCRIPTION
**Pull request by rw4nn**
Resolves #766.

Implementing the two update paths to Pro : 

System > Update -> just brings user to https://tinypilotkvm.com/product/tinypilot-pro?ref=tinypilot-app

System > Virtual Media -> Shows a dialog saying that this feature is available in TinyPilot Pro with a button to upgrade, which points to https://tinypilotkvm.com/product/tinypilot-pro?ref=tinypilot-app

---
This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/783)

### CODE REVIEW

**Comment by mtlynch** [comment]
Sorry, I used the wrong word in the original bug. I said "update" when I meant to say "upgrade." We should keep the existing "System > Update" item and leave that as-is, but we should add an additional option "System > Upgrade."

Sorry for the screwup! Can you bring back the update button and dialog?

**Comment by rw4nn** [comment]
Okay no worries, I brought back the update button / dialog, should be fine now :sweat_smile:

**Review by mtlynch — CHANGES_REQUESTED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/783#-:-MibpBMu1KR1IH0-JjDs:brfqlux)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[app/templates/custom-elements/feature-pro-dialog.html, line 19 at r2](https://reviewable.io/reviews/tiny-pilot/tinypilot/783#-MibnquR1mY5wdBL93vB:-MibnquR1mY5wdBL93vC:b-605zod) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/649aa73269b441c790dac494c72464cc348ecb9c/app/templates/custom-elements/feature-pro-dialog.html#L19)):*
> ```HTML
>   import { DialogClosedEvent } from "/js/events.js";
> 
>   (function () {
> ```

Now that we're using ES6 modules, we don't need the `(function () {...})()` anymore. We're leaving it in old components to avoid churning the whole file, but we can skip it for new components.
___
*[app/templates/custom-elements/menu-bar.html, line 195 at r2](https://reviewable.io/reviews/tiny-pilot/tinypilot/783#-Mibo_Gl4deOGODJA2Vx:-Mibo_Gm55dSOIewu3FW:b-rkkqwq) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/649aa73269b441c790dac494c72464cc348ecb9c/app/templates/custom-elements/menu-bar.html#L195)):*
> ```HTML
>           <a id="power-btn">Power</a>
>         </li>
>         <li class="item">
> ```

Can we move this to below Update? I'd like to keep Power last.

**Comment by rw4nn** [comment]
Ok thanks for the review, updated :+1: Squash/merging now.

**Pull request merged**
