### PR TITLE
TinyPilot WiFi access point scripts

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/tinypilot/issues/1711

This PR converts the individual code snippets from [our blog post on how to host a WiFi access point on your TinyPilot device](https://tinypilotkvm.com/faq/wifi-ap/), into less intimidating scripts:
* `enable-wifi-ap`
* `disable-wifi-ap`

Notes:
1. Most of the code is copy-pasted from the blog post with minor enhancements made.
2. All the default settings have been preserved.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1778">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:

```
> Line 48
      ;;
```
We want defaults for SSID and country, but we should provide flags that allow the user to override them.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:

```
> Line 55
      ;;
```
Oh right, I forgot about that. Thanks.


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778)



<hr />

In: **Discussion**
I'm actually not 100% sure what's going on in these scripts... but I can find out and add comments.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/disable-wifi-ap**:
Done.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:
Done.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:
Done.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:
Yes it was, with the intention of it being a section divider (because the comment applies to the next several lines of code).

But if it sparks slight confusion, I would rather default to a normal comment instead. Fixed.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:

```
> Line 88
# Validate command-line arguments.
```
Done.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:

```
> Line 118
"${SCRIPT_DIR}/strip-marker-sections" /etc/dhcpcd.conf
```
Yes, that's correct. I've added a note to the help output. Thanks!


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778)



<hr />

In: **Discussion**
Good idea! Tracking in https://github.com/tiny-pilot/tinypilot/pull/1784

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/enable-wifi-ap**:
Ah good catch, thanks.


<hr />

👀 @mtlynch it's your turn please take a look

**Pull request merged**
