### PR TITLE
Log whether the user is using the TinyPilot mouse jiggler

### PR DESCRIPTION
**Pull request by db39**
This change adds the state of the TinyPilot mouse jiggler to the debug logs under the TinyPilot state section.

We had one instance in the past where a hanging mouse jiggler caused issues with the mouse, so logging the state of our own mouse jiggler may help with debugging issues in the future.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1475">Review on CodeApprove</a>

### CODE REVIEW

**Comment by db39** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1475)

⏳ @mtlynch please review this Pull Request

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1475)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1475)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM!

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 113
print_info "Checking if mouse jiggler is enabled..."
```
Seeing as we're not using variable interpolation, can we use single quotes here?

(Same for `MOUSE_JIGGLER_STATUS`)

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Can we remove this blank line?


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1475)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 113
print_info "Checking if mouse jiggler is enabled..."
```
Yeah I'm happy to make those changes. However, I basically copied the conventions from the [SSH status](https://github.com/tiny-pilot/tinypilot/blob/master/debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs#L103) section. It looks like the whole file follows the same convention of using double quotes almost exclusively. It feels wrong to make changes to a single block, so it might be better to make these changes for the whole file, or stick with the current file's (incorrect) convention for consistency.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1475)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1475">Approved on CodeApprove</a>
✔️ Approved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Ah, yeah sure, we can keep it as is.


<hr />

👀 @db39 it's your turn please take a look

**Pull request merged**
