### PR TITLE
Place temporary install files within RAMdisk

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1462

You can test this PR's install script and bundle via:
```bash
curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/aca37b26108c7fc7fc24fad48890734859fe9221/get-tinypilot.sh | \
    bash -
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1464">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1464)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1464)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **get-tinypilot.sh**:

```
> Line 72
 readonly RAMDISK_SIZE_MIB=500
```
Can we update this to 560? We expect about 50 MiB of temp files + 20% slop.

<hr />

In: **get-tinypilot.sh**:

```
> Line 115
  # file before the end of the script for some reason. We use /var/tmp as a
```
I'd say "begins purging files" since now it's more than one.

<hr />

In: **get-tinypilot.sh**:

```
> Line 123
# Use a temporary directory within the installer directory.
```
Suggest:

>Use a temporary directory within the installer directory so that we take advantage of RAMdisk if we're using one.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1464)



<hr />

In: **get-tinypilot.sh**:
Done.

<hr />

In: **get-tinypilot.sh**:
Thanks, done.

<hr />

In: **get-tinypilot.sh**:
Thanks, done.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1464)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
