### PR TITLE
Refactor attachShadow calls

### LINKED ISSUE #718: Refactor attachShadow calls
All of our HTML custom elements include this snippet:

```javascript
this.attachShadow({ mode: "open" })
this.shadowRoot.appendChild(template.content.cloneNode(true));
```

But `attachShadow` [returns the shadow root](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow), so we can just do it in a single statement:

```javascript
this.attachShadow({ mode: "open" }).appendChild(template.content.cloneNode(true));
```

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #718
Hi @mtlynch, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by mtlynch** [comment]
Cool, thanks! Can you run `npm run format` so that it fixes the build break?

https://github.com/mtlynch/tinypilot/blob/master/CONTRIBUTING.md

**Comment by RhnSharma** [comment]
@mtlynch I fixed the formatting but I'm not able to commit the changes.

**Comment by mtlynch** [comment]
@RhnSharma - Can you share more details? What's preventing git from committing the changes?

**Comment by mtlynch** [comment]
@RhnSharma are you still working on this or should I close?

**Comment by RhnSharma** [comment]
@mtlynch There are no errors. This happens whenever I try to commit the changes.

https://user-images.githubusercontent.com/22129063/121294899-c14ffc80-c90b-11eb-8fa3-97265faac817.mp4

**Comment by mtlynch** [comment]
It looks like your version of YAPF doesn't match the version required, so the pre-commit checks are failing. You can either [configure your development environment](https://github.com/tiny-pilot/tinypilot/blob/master/CONTRIBUTING.md#setting-up-a-development-environment) to match the required settings.

The easier option is to just skip the pre-commit checks with `-n`:

```bash
git commit -m "Fix formatting" --no-verify
```

**Comment by mtlynch** [comment]
Thanks, @RhnSharma !

**Pull request merged**
