### PR TITLE
Consume paste API endpoint

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1026

This PR consumes the new `/api/paste` endpoint and removes the, now-unused, text-to-keystroke frontend logic.

Demo video:

https://github.com/tiny-pilot/tinypilot/assets/6730025/2b3cb2c9-964b-4e90-88c9-7ab13775f02b

### Notes
1. Pasting unsupported characters (i.e., `“`, `”`, `–` (en-dash), `—` (em-dash), etc.) now displays this error dialog:
    
    Screen Shot 2023-09-15 at 11 20 21

    Previously, these unsupported characters were silently ignored during a paste.
    As [discussed here](https://github.com/tiny-pilot/tinypilot/pull/1545#issuecomment-1711939987), we plan to further refine this behavior in the future.

### Peer testing
This PR is stacked onto the following PRs:
* https://github.com/tiny-pilot/tinypilot/pull/1625
* https://github.com/tiny-pilot/tinypilot/pull/1624

You can test them all on device via the following command:
```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- https://output.circle-artifacts.com/output/job/d842ed53-55a6-490d-9cfd-842155c7d6e5/artifacts/0/bundler/dist/tinypilot-community-20230919T1127Z-1.9.1-39+3e308b3.tgz && \
  sudo reboot
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1626">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1626)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1626)



<hr />

In: **app/static/js/app.js**:
Oh nice, thanks!

**Comment by jdeanwallace** [comment]
@db39 - Could you please test the "Paste" functionality of this PR on a device while using a laptop or desktop computer as a target machine?

[Jan experienced some mismatching/missing characters during a paste](https://codeapprove.com/pr/tiny-pilot/tinypilot/1625#thread-012f3a48-81af-4dd0-b496-c5a41a021f38), but I'm unable to reproduce it. We think it might be because he's using a lower-powered target machine. If this PR works for a regular target machine, then it should be safe to merge.

You can use [this text for copy/pasting](https://gist.github.com/jotaen4tinypilot/468f6f1337125908600fd7d24091d501) and the following command to install the bundle:

```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- https://output.circle-artifacts.com/output/job/a4949eb7-1dba-4f2e-a059-e5c3d8b817e7/artifacts/0/bundler/dist/tinypilot-community-20230915T0920Z-1.9.1-23+24ca079.tgz && \
  sudo reboot
```

**Comment by mtlynch** [comment]
>We think it might be because he's using a lower-powered target machine. If this PR works for a regular target machine, then it should be safe to merge.

I'd like to dig into this further before merging. Pasting incorrect text is a step down from the currently-released behavior of stopping after too many characters.

@db39 - Hold off on testing this.

**Pull request merged**
