### PR TITLE
Reimplement /boot/config.txt logic in postinst script

### LINKED ISSUE #1594: Reimplement `/boot/config.txt` logic in postinst script
The uStreamer Ansible role currently makes two modifications to `/boot/config.txt` if the TC358743 is enabled:

It adds the line `dtoverlay=tc358743-audio` immediately after the line `dtoverlay=tc35843`:

https://github.com/tiny-pilot/tinypilot/blob/c0d8e10628afe0ca5ff2116308a51c3c1e21f9a3/ansible-role-ustreamer/tasks/provision_tc358743.yml#L2-L8

It writes `gpu_mem=256` at the end of the file or overwrites the line if a line beginning with `gpu_mem=` already exists in the file:

https://github.com/tiny-pilot/tinypilot/blob/c0d8e10628afe0ca5ff2116308a51c3c1e21f9a3/ansible-role-ustreamer/tasks/provision_tc358743.yml#L10-L16

We can reimplement this logic in [`tinypilot.postinst`](https://github.com/tiny-pilot/tinypilot/blob/c0d8e10628afe0ca5ff2116308a51c3c1e21f9a3/debian-pkg/debian/tinypilot.postinst) to trim out Ansible logic.

We have an example of checking for if TC358743 is enabled:

https://github.com/tiny-pilot/tinypilot/blob/572ee6acfd459946ce9a5b4a448d31f6dd4cbdca/debian-pkg/debian/tinypilot.postinst#L119

It's a little bit out of scope, but we should also take this opportunity to reimplement `janus.plugin.ustreamer.jcfg` in the `tinypilot.postinst` using [render-template](https://github.com/tiny-pilot/tinypilot/blob/c0d8e10628afe0ca5ff2116308a51c3c1e21f9a3/debian-pkg/debian/tinypilot.postinst#L74-L79). That way, we can test the changes all at the same time, and it lets us completely get rid of all the Ansible logic around `/boot/config.txt`:

https://github.com/tiny-pilot/tinypilot/blob/c0d8e10628afe0ca5ff2116308a51c3c1e21f9a3/ansible-role-ustreamer/tasks/main.yml#L2-L27

### PR DESCRIPTION
**Pull request by db39**
Resolves #1594

These changes remove some `ansible` tasks relating to the `/boot/config.txt` logic and re-implements them using `tinypilot.postinst` instead.

To test on a live device:

```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- \
    https://output.circle-artifacts.com/output/job/743a657b-dbde-48b6-912e-01ee511631f0/artifacts/0/bundler/dist/tinypilot-community-20230901T1138Z-1.9.0-72+c746cda.tgz
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1602">Review on CodeApprove</a>

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1602)



Sorry to peek, but just wanted to leave some early notes to avoid going too far in testing this behavior.

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 96
if grep --silent '^dtoverlay=tc358743$' "${BOOT_CONFIG_PATH}" ; then
```
Since we do this check elsewhere, it's probably worth saving the result to [a boolean variable](https://github.com/tiny-pilot/tinypilot/blob/701429338473d328e7d432067750b507d3296195/debian-pkg/debian/tinypilot.postinst#L119) so we can reuse it.

You can see an example of us using a boolean variable in bash in [`change-hostname`](https://github.com/tiny-pilot/tinypilot/blob/701429338473d328e7d432067750b507d3296195/debian-pkg/opt/tinypilot-privileged/scripts/change-hostname#L69-L70).

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 102
if grep --silent '^gpu_mem=' "${BOOT_CONFIG_PATH}" ; then
```
We want to do this *only* if TC358743 mode is enabled.


<hr />

👀 @db39 it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1602)



<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 118
{% if tc358743_overlay_enabled -%}
```
Sorry, I'm realizing `render-template` isn't going to work here because it only knows about the variables in [`settings.py`](https://github.com/tiny-pilot/tinypilot/blob/50e7e583472984bbe50c375a4d4f5a29c2079d11/app/update/settings.py). We could theoretically extend it to accept extra vars, but I think this file is so simple that we might as well just construct it with plain bash. Like write the first part and then if `tc358743_overlay_enabled ` is true, append the second part.


<hr />

👀 @db39 it's your turn please take a look

**Comment by db39** [comment]
Thanks for mentioning that! I noticed `render-template` wasn't going to work without some modifications, so I thought it was a little odd to use it.

**Comment by db39** [comment]
It looks like we can't quite remove all of the `/boot/config.txt` logic from `ansible-role-ustreamer/tasks/main.yml` because the [`configure TC358743 HDMI capture chip`](https://github.com/tiny-pilot/tinypilot/blob/c746cdad68d7a083ffa0bfe625ad04cb904cf7aa/ansible-role-ustreamer/tasks/main.yml#L36C1-L38C35) task relies on it.

It looks like the `configure TC358743 HDMI capture chip` task will be removed in #1598. Should I wait until that's complete?

**Comment by mtlynch** [comment]
>It looks like we can't quite remove all of the /boot/config.txt logic from ansible-role-ustreamer/tasks/main.yml because the configure TC358743 HDMI capture chip task relies on it.

Ah, right.

>It looks like the configure TC358743 HDMI capture chip task will be removed in #1598. Should I wait until that's complete?

No, how you have it now is good, and I'll remove the leftover `/boot/config.txt` stuff in #1598.

**Comment by db39** [comment]
I tested installations with `dtoverlay=tc358743` and without - both `/boot/config.txt` and `/etc/janus/janus.plugin.ustreamer.jcfg` contain the appropriate content after install.

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1602)



<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
Resolved

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
Resolved

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 95
if grep --silent '^dtoverlay=tc358743$' "${BOOT_CONFIG_PATH}" ; then
```
Resolved


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1602)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1602">Approved on CodeApprove</a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @db39 it's your turn please take a look

**Pull request merged**
