### PR TITLE
Drop support for building uStreamer from source

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1428

This PR removes references to `ustreamer_repo` and `ustreamer_repo_version` variables, which makes `ustreamer_debian_package_path` a  required variable.

Notes:
1. We no longer need to install `janus-dev` because our uStreamer Debian package already includes the compiled uStreamer Janus plugin (i.e., `libjanus_ustreamer.so`) 
2. I've also updated `ansible-role-ustreamer/README.md` to reflect these variable changes
3. Now that `ustreamer_debian_package_path` is required and our custom uStreamer Debian package requires Janus, we could [possibly remove the `ustreamer_install_janus` flag](https://github.com/tiny-pilot/tinypilot/blob/5e82ffef3fb66b65706ab5ca77533d89a8fad3f9/ansible-role-ustreamer/tasks/main.yml#L16-L18) because it must always be installed. However, `ansible-role-ustreamer` is still somewhat generic and [allows H264 streaming to be disabled](https://github.com/tiny-pilot/tinypilot/blob/5e82ffef3fb66b65706ab5ca77533d89a8fad3f9/ansible-role-ustreamer/tasks/main.yml#L5-L14).
4. Now that `ustreamer_debian_package_path` is required, I've moved it's definition to [`ansible-role-ustreamer/vars/main.yml`](https://github.com/tiny-pilot/tinypilot/blob/1d85c6f74c71d3f32f883e612d6252dfc89a01a1/ansible-role-ustreamer/vars/main.yml#L1-L3) because we don't need to allow users to specify their own `ustreamer_debian_package_path` value.

You can test this PR by running the following on your device:
```bash
apt-get remove ustreamer --yes && \
  /opt/tinypilot/scripts/install-bundle \
    https://output.circle-artifacts.com/output/job/00360b5c-8004-41f4-ba33-2805de669392/artifacts/0/bundler/dist/tinypilot-community-20230628T1347Z-1.9.0-22+e254ba4.tgz
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1458">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1458)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1458)



<hr />

In: **ansible-role-ustreamer/defaults/main.yml**:
You're right. I wasn't sure how to specify a required Ansible variable, but then I [found this suggestion in the docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#defining-mandatory-values):
```yaml
galaxy_api_key: "{{ undef(hint='You must specify your Galaxy API key') }}"
```

EDIT: Nevermind, I couldn't get `undef` to work or it doesn't work in the way I expected.

<hr />

In: **ansible-role-ustreamer/defaults/main.yml**:
Thanks @mtlynch, that helped. We now only define and assign `ustreamer_debian_package_path` once in ansible-role-ustreamer/vars/main.yml.

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1458)



<hr />

In: **ansible-role-ustreamer/README.md**:

```
> Line 14
ustreamer_debian_package_path: ustreamer_0.0-00000000000000_armhf.deb
```
This part can be gone now, right?


<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by jdeanwallace** [comment]
@mtlynch - This PR is blocked on your review even though your comment has been resolved and the PR has been approved. Re-synchronize the PR via CodeApprove doesn't fix it.

**Pull request merged**
