### PR TITLE
Install Janus config files from TinyPilot Debian package

### LINKED ISSUE #1496: Install Janus config files from TinyPilot Debian package
~~Blocked on https://github.com/tiny-pilot/tinypilot-pro/pull/985~~

We're currently placing Janus' config files using Ansible:

https://github.com/tiny-pilot/tinypilot/blob/d903d32f890505e97f94ec1c4549648037dc3555/ansible-role-ustreamer/tasks/install_janus.yml#L21-L32

It should be trivial to pull this logic out of Ansible and implement it instead in TinyPilot's Debian package.

Some notes on the migration:

* The Ansible task is a `template` task even though the source files don't have any templated values. I don't know if this was a mistake originally or if they used to have templates, but now they're just static files.
  * This makes the task easier, as we should be able to move the files like this:
    * `ansible-role-ustreamer/templates/janus.jcfg.j2` -> `debian-pkg/etc/janus/janus.jcfg`
    * `ansible-role-ustreamer/templates/janus.transport.websockets.jcfg.j2` -> `debian-pkg/etc/janus/janus.transport.websockets.jcfg`
* The Ansible task templatizes the path based on `ustreamer_janus_configs_dir`, but we can hardcode the path to `/etc/janus` for simplicity.
* We don't have to implement logic for restarting the Janus service.
* We should preserve `root` as the user and group.
* We should preserve `0644` as the permissions, but if that generates a CI error in lintian, we should accept lintian's suggestion. The important thing is that the execute bit is off for everyone and the write bit is off for non-owner.

## Similar work

* https://github.com/tiny-pilot/tinypilot/pull/1412

### PR DESCRIPTION
**Pull request by db39**
Resolves #1496

This change replaces the Ansible task responsible for creating the Janus config files, implementing it in TinyPilot's Debian package instead.

To test this bundle, run:

```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- \
    https://output.circle-artifacts.com/output/job/5e8d773d-c381-465e-bd67-425ff99f5cd3/artifacts/0/bundler/dist/tinypilot-community-20230804T1445Z-1.9.0-46+dd77b49.tgz
```
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1552">Review on CodeApprove</a>

### CODE REVIEW

**Comment by db39** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)



<hr />

In: **Discussion**
I'm getting the following installation error when installing this PR's bundle on a fresh device:

```
Unpacking tinypilot (20230803145533) ...
dpkg: error processing archive /mnt/tinypilot-installer/tinypilot_20230803145533_armhf.deb (--unpack):
 trying to overwrite '/etc/janus/janus.jcfg', which is also in package janus 1.0.1-1~bpo11+1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /mnt/tinypilot-installer/tinypilot_20230803145533_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The problem is that two different Debian packages (i.e.,`janus` & `tinypilot`) can't be responsible for the same file (i.e., `/etc/janus/janus.jcfg`).

I faced a similar issue when trying to install our [custom NGINX config](https://github.com/tiny-pilot/tinypilot/blob/470a9444f8ca61509ab7a782290a131e87744117/debian-pkg/usr/share/tinypilot/nginx.conf) to `/etc/nginx/nginx.conf` because the `nginx` Debian package created it initially.

The workaround is to place the `janus.jcfg` in `debian-pkg/usr/share/tinypilot/` and then overwrite `/etc/janus/janus.jcfg` in the `tinypilot.postinst` script ([similar to how we install `nginx.conf`](https://github.com/tiny-pilot/tinypilot/blob/470a9444f8ca61509ab7a782290a131e87744117/debian-pkg/debian/tinypilot.postinst#L88-L90)).


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)



<hr />

In: **Discussion**
I missed that error - but it does appear on my device, sorry about that.

Thanks for the guidance! I think I've got it working as expected now. I wasn't sure whether we need to only overwrite the files on a certain condition or not, so right now `tinypilot.postinst` just overwrites the files regardless.






<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

Nice, LGTM!

<hr />

In: **Discussion**
Can we also remove the unused template files?
* `ansible-role-ustreamer/templates/janus.jcfg.j2`
* `ansible-role-ustreamer/templates/janus.transport.websockets.jcfg.j2`

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
(nit) Can we remove the empty line? That way the two commands looks grouped together because they both deal with placing Janus config.


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)



<hr />

In: **Discussion**
Resolved

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
Resolved

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1552)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
