### PR TITLE
Improve CPU throttle lines in TinyPilot logs

### LINKED ISSUE #1489: Improve CPU throttle lines in TinyPilot logs
The CPU throttle line is currently inconsistent with most other lines in the TinyPilot logs.

We should clean it up to be more user-friendly and consistent with our other lines.

### Current

```text
throttled=0x0
```

### Desired

```text
CPU throttled since boot: No
```

### PR DESCRIPTION
**Pull request by cghague**
Resolves #1489

Parses the output of `vcgencmd get_throttled` into a simple “yes” or “no” result.

## Decoding the output of `vcgencmd get_throttled`

We could decode the output of `vcgencmd get_throttled` to get more details, but for our purposes we simply want to detect that nothing relating to throttling has occurred since the device was booted, a situation  which is indicated by an output value of `0x0`.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1543">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1543)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1543)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **Discussion**
With regards to consistency, https://github.com/tiny-pilot/tinypilot/issues/1489 suggests:
```
CPU throttled since boot: No
```

However, I think the current style of the rest of the logs is for the value after the colon to be lowercase. For example:
```
TinyPilot state
Read-only filesystem: off
SSH access: enabled
Mouse jiggler: disabled
```

Can we use a lowercase "yes"/"no"?

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 139
  if vcgencmd get_throttled | grep -q "0x0" ; then
```
I'm not sure what all the possible outputs of `vcgencmd get_throttled` can be, but just to be safe can we make sure that `grep` matches the entire line exactly?

Something like:
```bash
if vcgencmd get_throttled | grep --line-regexp -q '0x0' ; then
```


<hr />

👀 @cghague it's your turn please take a look

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1543)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 137
printf "%s\n\n" "$(vcgencmd get_throttled)" >> "${LOG_FILE}"
```
Also, can we preserve the extra newline?

Before:

 


After:

 



<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1543)



<hr />

In: **Discussion**
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Great point! Resolved.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 137
printf "%s\n\n" "$(vcgencmd get_throttled)" >> "${LOG_FILE}"
```
Resolved

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1543)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
