### PR TITLE
Fix tc358743 identifier in the /boot/config.txt population

### PR DESCRIPTION
**Pull request by mtlynch**
This fixes a small bug in the tinypilot.postinst that was preventing it from matching the right line in `/boot/config.txt` to add the `dtoverlay=tc358743-audio` line.

## Peer testing

To test this bundle run:

```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- \
    https://output.circle-artifacts.com/output/job/0bcd7da3-9a88-4126-ada8-6a7804e02dfe/artifacts/0/bundler/dist/tinypilot-community-20230901T1500Z-1.9.0-75+03827f4.tgz && \
  sudo reboot
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1617">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1617)

⏳ @db39 please review this Pull Request

**Comment by mtlynch** [comment]
@db39 - Can you try the peer test on a bare Raspbian system [with TC358743 enabled](https://github.com/tiny-pilot/tinypilot/wiki/Installation-Options#example-tc358743-hdmi-to-csi-capture-chip) and make sure you hear audio? I'm getting inconsistent results with audio, but I still see the issue on 2.6.0, so I can't figure out if there's something off in my environment, or if there's something we've introduced in 2.6.1.

**Comment by db39** [comment]
@mtlynch - No worries - starting testing now.

**Comment by db39** [comment]
Audio worked fine in my testing (bare Raspian Bullseye 32-bit).

**Review by db39 — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1617)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1617">Approved on CodeApprove</a>
✔️ Approved

LGTM!

<hr />

👀 @mtlynch it's your turn please take a look

**Comment by mtlynch** [comment]
Great, thanks!

**Pull request merged**
