### PR TITLE
Add element naming conventions to CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/884

---
This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895)

### CODE REVIEW

**Review by jotaen4tinypilot — COMMENTED** [review]
Would we always reference elements via `class` now, or only if there are multiple dialog states involved?

I’m happy with either, I just wasn’t 100% sure how we wanted it:

- In case we still allow to reference by `id` for “single-state” dialogs, we could split up the section into two subsections, one for each case.
- In case we always want to reference by `class` (even for “single-state” dialogs), I think it would be clearer if we first say how we want it, and then give a (shorter) background about why we decided that way. Currently, the most important statement is at the very bottom, but I feel it should be right at the beginning instead.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-:-MuC4KeE8hsk_QMt3Whq:b4w0af5)* status: 0 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 270 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-MuC40jGDG2-5_wWs8SA:-MuC40jH03TdyxikgXhC:bich50l) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/00e164d6868be76013aab0d4a688dfb650ac043e/CONTRIBUTING.md#L270)):*
> ```Markdown
> ```
> 
> ### Naming DOM elements
> ```

Suggest: `Referencing DOM elements` or `Referencing DOM elements from JavaScript`

**Review by mtlynch — COMMENTED** [review]
> Would we always reference elements via class now, or only if there are multiple dialog states involved?

I think we should only do it in the case of naming conflicts. `getElementById` is nice and unambiguous, so I'd like for us to be able to use it where possible.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-:-MuCGwxL7kUbQgh8dccS:b-r0q5cd)* status: 0 of 1 LGTMs obtained

**Review by jotaen4tinypilot — COMMENTED** [review]
> I think we should only do it in the case of naming conflicts. getElementById is nice and unambiguous, so I'd like for us to be able to use it where possible.

:thumbsup: thanks for clarifying. In this case I think it would be cool to divide the text into two subsections. To me, that would make it more obvious that we allow two ways that each have their own precondition. Other than that, the text and the examples look well written and clear to me!

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-:-MuG3DoA2UzNsL3FIGxB:b-ew8t8e)* status: 0 of 1 LGTMs obtained

**Review by jdeanwallace — COMMENTED** [review]
> Would we always reference elements via class now, or only if there are multiple dialog states involved?
 
@jotaen Sorry for the confusion. Yes what I meant is that we should reference elements using the `class` attribute only if there are multiple states involved.

---

> Currently, the most important statement is at the very bottom, but I feel it should be right at the beginning instead.

@jotaen I've [moved this statement to the top](https://github.com/tiny-pilot/tinypilot/pull/895/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R272) of the section and reworded it distinguish between "single-state" and "multi-state" situations.

---

> In case we still allow to reference by id for “single-state” dialogs, we could split up the section into two subsections, one for each case.

@jotaen With the most recent changes, does it still warrant an additional section to outline the classic "reference by ID" case? I'm just worried that this section becomes too lengthy.

> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-:-MuLart3-6TgrR4yw2o2:b-r2mn74)* status: 0 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 270 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-MuC40jGDG2-5_wWs8SA:-MuLagSo0HiCXevI82ae:b-896fix) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/00e164d6868be76013aab0d4a688dfb650ac043e/CONTRIBUTING.md#L270)):*
<details><summary><i>Previously, jotaen4tinypilot wrote…</i></summary><blockquote>

Suggest: `Referencing DOM elements` or `Referencing DOM elements from JavaScript`
</blockquote></details>

Done.

**Review by jotaen4tinypilot — APPROVED** [review]
:lgtm: I think it’s clear now, thanks for the change!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/895#-:-MuMNxxK2QwyGWsmJHQ3:b-qy3vbw)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
