### PR TITLE
Refactor HID write timeout logic

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/tinypilot/issues/1026

This PR moves the multiprocessing timeout logic to a separate `execute` module, along with other related classes. This change simplifies the `hid.write` module by stripping out multiprocessing details not directly related to writing to the HID interface.

### Notes
1. We've moved the following classes to the new `execute` module:
    * `ProcessWithResult`
    * `ProcessResult`
1. We've moved the HID write timeout logic to a generic `execute.with_timeout` function
2. We've moved `hid.write_test.py` to `execute_test.py`
3. I'm not really sure why we need this function or if it is still required, but I kept it around anyway:
https://github.com/tiny-pilot/tinypilot/blob/106e6448bd931da40f9e49c5fc97d5970fffa6d6/app/process.py#L84-L87

### Peer testing
You can test this build by running the following command on a device:
```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- \
    https://output.circle-artifacts.com/output/job/5789b04e-8216-42fe-ad1e-227948464d03/artifacts/0/bundler/dist/tinypilot-community-20230907T1543Z-1.9.1-12+e1ba857.tgz
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1621">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)



<hr />

In: **app/hid/write.py**:

```
> Line 37
                             buffer)
```
The semantics make the code a little hard to read at the callsite. It's not obvious what `0.5` is, and then we can't name the parameter because then we have to name every subsequent parameter.

Could we make it like:

```python
process.with_timeout(lambda: _write_to_hid_interface_immediately(hid_path, buffer),
                     timeout_in_seconds=0.5)
```

<hr />

In: **app/process_test.py**:

```
> Line 6
from process import ProcessResult
```
Imports need to be at module level.

https://google.github.io/styleguide/pyguide.html#22-imports

I assume this is to avoid the naming collision with the variable named `process`, which is another compelling reason to rename the module.

<hr />

In: **app/process.py**:

```
> Line 1
import dataclasses
```
I'm not crazy about `process` as a module name.

The fact that we're using processes vs. threads is an implementation detail, so I don't want to highlight that. Plus, there's ambiguity in whether by "process" we're referring to the verb ("process this function") or the noun ("run this function in a separate process").

What about `execute`?


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)



<hr />

In: **app/execute.py**:

```
> Line 1
import dataclasses
```
Good point, done.

<hr />

In: **app/hid/write.py**:
It looks like lambda's don't play well with multiprocessing (& multithreading). We get this error when trying to start a lambda in a process:
```
Traceback (most recent call last):
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jason/repos/tinypilot/tinypilot/venv/lib/python3.9/site-packages/socketio/server.py", line 733, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/jason/repos/tinypilot/tinypilot/venv/lib/python3.9/site-packages/socketio/server.py", line 758, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/jason/repos/tinypilot/tinypilot/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/Users/jason/repos/tinypilot/tinypilot/venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "/Users/jason/repos/tinypilot/tinypilot/app/socket_api.py", line 58, in on_mouse_event
    fake_mouse.send_mouse_event(mouse_path, mouse_move_event.buttons,
  File "/Users/jason/repos/tinypilot/tinypilot/app/hid/mouse.py", line 17, in send_mouse_event
    hid_write.write_to_hid_interface(mouse_path, buf)
  File "/Users/jason/repos/tinypilot/tinypilot/app/hid/write.py", line 36, in write_to_hid_interface
    execute.with_timeout(
  File "/Users/jason/repos/tinypilot/tinypilot/app/execute.py", line 70, in with_timeout
    process.start()
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/jason/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'write_to_hid_interface.<locals>.<lambda>'
```

This is fixable with `functools.partial`, but then the callsite looks like this:

```python
execute.with_timeout(functools.partial(
    _write_to_hid_interface_immediately, hid_path, buffer),
                        timeout_in_seconds=0.5)
```

I think the above looks bad too. So I went with this:
```python
execute.with_timeout(_write_to_hid_interface_immediately,
                     args=(hid_path, buffer),
                     timeout_in_seconds=0.5)
```

<hr />

In: **app/process_test.py**:
Yeah 😅. Resolved by renaming the module to `execute`.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — DISMISSED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **app/execute.py**:

```
> Line 63
        kwargs: Optional `function` keyword arguments as a dictionary.
```
Let's leave this out since we're not actually using it.

<hr />

In: **app/hid/write.py**:
Ah, bummer about `lambda`!

I think the rewrite is still pretty clear, even without the lambda.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)



<hr />

In: **app/execute.py**:
Done.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1621)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
