### PR TITLE
Release modifier keycodes when browser window loses focus.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/361

Background:
For normal keys (i.e., non-modifier keys) we [automatically release the key after being pressed](https://github.com/tiny-pilot/tinypilot/blob/86fae61abb9502fe87d487c6f9da5abd7416c272/app/hid/keyboard.py#L10-L18). We don't do this for modifier keys, instead we wait for the "keyup" event to fire.

When a user presses `ALT+TAB` to change applications on their host machine, the "keydown" events would fire, but the "keyup" events do not fire because the focus has already been switched to a different application when the keys are eventually released. From the target machine's perspective, this causes the modifier keys to appear stuck.

To avoid this, we release any modifier keys currently being pressed once the browser window loses focus.

### Caveat
[As mentioned in the issue thread](https://github.com/tiny-pilot/tinypilot/issues/361#issuecomment-1420780726), there exists a case where this PR does not fix the issue:
> users will still experience the bug if they use `ALT+TAB`/`CMD+TAB` to "change" to the **same** application.

However, this is [still considered an decent enough fix](https://github.com/tiny-pilot/tinypilot/issues/361#issuecomment-1420816354):
> I think even if we can reduce the bug to only happen when you Alt+Tab back into the original window, that's still a decent fix.

### How to test

You can [use `evtest`](https://github.com/tiny-pilot/tinypilot/issues/361#issuecomment-1419699354) to confirm the fix.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1296">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1296)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1296)



<hr />

In: **app/static/js/keyboardstate.js**:

```
> Line 27
  get state() {
```
+1 - Giving up the whole internal state breaks the encapsulation a lot, so it opens the door to confusing misuse.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1296)



<hr />

In: **app/static/js/app.js**:

```
> Line 320
      onKeyUp(/*keyboardEvent=*/ { code: keyCode });
```
Oh thanks, it should actually only release modifier keys. Fixed, I forgot to check using `isModifierCode`.

<hr />

In: **app/static/js/keyboardstate.js**:

```
> Line 25
   * @returns Object {[keyCode:string]: [isPressed:boolean]}
```
Well the thing is... I just made up my own syntax (a cross between JSDocs & JS syntax) because:
1. I didn't recognise the JSDoc syntax in the [rest of the file](https://github.com/tiny-pilot/tinypilot/blob/6124144fd9f4a813299e3a5f920b4e5e5a6c4ad1/app/static/js/keyboardstate.js#L32-L33)
2. The returned object is slightly unique because it uses dynamic keys, and I couldn't find an example on how to describe it

However, based on the other comments, I'll remove this code block.

<hr />

In: **app/static/js/keyboardstate.js**:

```
> Line 27
  get state() {
```
The reason why I call [`onKeyUp`](https://github.com/tiny-pilot/tinypilot/blob/91a6b1399a06e94a76f5624f9c8cbce7e0af4d2b/app/static/js/app.js#L210-L227) is because I didn't want to copy-paste the [business logic of releasing a key](https://github.com/tiny-pilot/tinypilot/blob/91a6b1399a06e94a76f5624f9c8cbce7e0af4d2b/app/static/js/app.js#L218-L226) (i.e., update keyboard state, check socket connection, release key). I wanted to avoid creating an additional way of releasing a key.

Seeing as there's a bunch of ways to do this, which would you recommend?

### A

```javascript
window.addEventListener("blur", () => {
  if (keyboardState.isAnyModifierKeysPressed()) {
    keyboardState.releaseAllModifierKeys();
    if (!connectedToServer) {
      return;
    }
    socket.emit("keyRelease");
  }
});
```

### B

```javascript
window.addEventListener("blur", () => {
  const hasReleasedModifierKeys = keyboardState.releaseAllModifierKeys();
  if (hasReleasedModifierKeys) {
    if (!connectedToServer) {
      return;
    }
    socket.emit("keyRelease");
  }
});
```

### C

```javascript
window.addEventListener("blur", () => {
  if (keyboardState.isAnyModifierKeysPressed()) {
    keyboardState.reset(); // i.e., release all keys.
    if (!connectedToServer) {
      return;
    }
    socket.emit("keyRelease"); // i.e., release all keys.
  }
});
```

### D

```javascript
window.addEventListener("blur", () => {
  keyboardState.pressedKeys
    .filter((keyCode) => isModifierCode(keyCode))
    .forEach((keyCode) => onKeyUp({ code: keyCode }));
});
```


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1296)



<hr />

In: **app/static/js/app.js**:
Done.

<hr />

In: **app/static/js/keyboardstate.js**:
Thanks, done.

**Pull request merged**
