### PR TITLE
Convert paste-overlay to paste-dialog

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1137

This PR completely removes the old "Paste" frontend code and replaces it with a custom `<paste-dialog>` element.

https://github.com/tiny-pilot/tinypilot/assets/6730025/880e650f-b938-4fd6-8417-55c806cd6301

Notes:
1. Once the paste-dialog is open, you can just press the "Enter" key to actually paste it to the target machine. This is in accordance to our style guide:
    https://github.com/tiny-pilot/tinypilot/blob/273b200d9c49c453e753538393a4712f4755dd44/app/templates/styleguide.html#L260-L262
However, this behavior might be unexpected especially if you're manually typing text into the textarea and want to add a newline character. With this in mind, I made sure that you can still add a newline character using `Shift+Enter`.  

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1603">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1603)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1603)



Cool, I didn't realize how much complexity we'd eliminate by getting rid of the legacy overlay.

<hr />

In: **Discussion**
>Once the paste-dialog is open, you can just press the "Enter" key to actually paste it to the target machine. This is in accordance to our style guide:
https://github.com/tiny-pilot/tinypilot/blob/273b200d9c49c453e753538393a4712f4755dd44/app/templates/styleguide.html#L260-L262
However, this behavior might be unexpected especially if you're manually typing text into the textarea and want to add a newline character. With this in mind, I made sure that you can still add a newline character using Shift+Enter. 

I think this is the right behavior, but we shouldn't forward the `<Enter>` keystroke to the target system. Currently, it gets sent after the pasted text. For example, if I type `hi<Enter>`, the target system sees:

```text
2023-08-31 09:16:22.134 socket_api      DEBUG [SENSITIVE] received keystroke message: {'metaLeft': False, 'metaRight': False, 'altLeft': False, 'altRight': False, 'shiftLeft': False, 'shiftRight': False, 'ctrlLeft': False, 'ctrlRight': False, 'key': 'h', 'code': 'KeyH'} [/SENSITIVE]
2023-08-31 09:16:22.154 socket_api      DEBUG [SENSITIVE] received keystroke message: {'metaLeft': False, 'metaRight': False, 'altLeft': False, 'altRight': False, 'shiftLeft': False, 'shiftRight': False, 'ctrlLeft': False, 'ctrlRight': False, 'key': 'i', 'code': 'KeyI'} [/SENSITIVE]
2023-08-31 09:16:22.174 socket_api      DEBUG [SENSITIVE] received keystroke message: {'metaLeft': False, 'metaRight': False, 'altLeft': False, 'altRight': False, 'shiftLeft': False, 'shiftRight': False, 'ctrlLeft': False, 'ctrlRight': False, 'key': 'Enter', 'code': 'Enter'} [/SENSITIVE]
```

<hr />

In: **Discussion**
Can we disable the paste button when the `textarea` contains an empty string?

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:

```
> Line 17
  <h3>Paste Text to the Target System</h3>
```
Can we simplify this to "Paste Text"?

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:

```
> Line 19
    The target system needs to have an <i>en-US</i> or <i>en-GB</i> keyboard
```
Let's change this to:

```html
<p>
  Note: The target system must have an <span class="monospace">en-US</span> or
  <span class="monospace">en-GB</span> keyboard layout.
</p>
```

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:

```
> Line 50
            pasteArea: this.shadowRoot.querySelector("#paste-area"),
```
(nit) Suggest reordering either alphabetically or by order of appearance (top to bottom, left to right).


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1603)



<hr />

In: **Discussion**
Sure.

<hr />

In: **Discussion**
Oh, nice catch. Fixed.

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:
Done.

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:
Sure.

<hr />

In: **app/templates/custom-elements/paste-dialog.html**:
Thanks,  I went with order of appearance.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1603)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1603">Approved on CodeApprove</a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @jdeanwallace it's your turn please take a look

**Pull request merged**
