### PR TITLE
Add comments to wireless access point scripts

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/tinypilot/issues/1711

This is a follow-up PR to a [review comment](https://codeapprove.com/pr/tiny-pilot/tinypilot/1778#thread-4d8c230a-afdd-4361-8e21-0a7be15efb06) asking for more code comments in our `enable-wifi-ap` and `disable-wifi-ap` scripts.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1784">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1784)

⏳ @db39 please review this Pull Request

**Comment by jdeanwallace** [comment]
@db39 - Just checking to see if this is still on your radar?

**Comment by db39** [comment]
@jdeanwallace - Thanks for the ping on this - it completely fell off my radar. I'll review it today.

**Review by db39 — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1784)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1784">Approved on CodeApprove</a>
✔️ Approved

LGTM!

<hr />

👀 @jdeanwallace it's your turn please take a look

**Pull request merged**
