### PR TITLE
Replace Voyager 2 with Voyager 2a in README

### PR DESCRIPTION
**Pull request by mtlynch**
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1334">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1334)

⏳ @db39 please review this Pull Request

**Review by db39 — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1334)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

Other than the incorrect link in the heading, this looks good to me!

<hr />

In: **README.md**:

```
> Line 29
### [TinyPilot Voyager 2a](https://tinypilotkvm.com/product/tinypilot-voyager2)
```
It looks like this link still points to the Voyager 2 page instead of the 2a.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1334)



<hr />

In: **README.md**:
Ah, missed that! Thanks.

**Review by db39 — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1334)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
