### PR TITLE
Follow-up PR changes to using uStreamer launcher.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1258

This PR adds the follow-up non-functional changes suggested in the ["Use uStreamer launcher" PR review](https://github.com/tiny-pilot/tinypilot/pull/1252#pullrequestreview-1247918295).
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1259">Review on CodeApprove</a>

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1259)



<hr />

In: **app/templates/custom-elements/video-settings-dialog.html**:

```
> Line 453
              // returns an HTTP 200 OK response.
```
(nit) Technically, we're checking for a 2xx response, since anything in the 200-299 range is OK

https://developer.mozilla.org/en-US/docs/Web/API/Response/ok


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Comment by jdeanwallace** [comment]
@mtlynch - I know you're not the main reviewer, but this PR seems blocked on your early review comment.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1259)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1259">Approved on CodeApprove</a>
✔️ Approved

<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by mtlynch** [comment]
@jdeanwallace - Sorry about that. This is https://github.com/codeapprove/feedback/issues/80 . It might be solved by re-syncing CodeApprove, but I forgot to try that this time.

**Pull request merged**
