### PR TITLE
Update overhaul community release.

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1027

# Testing procedure

## Test update path from an existing TinyPilot installation

Follow these [install instructions](https://gist.github.com/jdeanwallace/9f293965f404a995c507e52afda1d39e).

### Bugs

1. <s>The `/opt/tinypilot-updater` directory is orphaned after an update.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1060

## Test new installation on fresh device

Follow these [install instructions](https://gist.github.com/jdeanwallace/a2cd6cf3aee3ff30c0f30891ba0aa356).

### Bugs

1. <s>Needs `sudo` priv when running `get-tinypilot.sh`.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1045

1. <s>Temp directory gets deleted before it is used.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1049

    * CircleCI logs: https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2311/workflows/a0d23ef4-f2e5-4283-820f-24fb5f9c651c/jobs/8705?invite=true#step-102-310

1. <s>Prevent `get-tinypilot.sh` from executing before the script is fully downloaded.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1052

1. <s>We get a `HTTP 404` on [some local project licenses](https://github.com/tiny-pilot/tinypilot/blob/0b25b86bbb84d835b3ea3cb6db84359ae6aba235/app/license_notice.py#L190) because the `/opt/tinypilot-updater` directory no longer exists. <s>Is it still worth referencing these licenses?</s></s>
    https://github.com/tiny-pilot/tinypilot/pull/1054

1. <s>`HTTP 500` error when running [`/opt/tinypilot-privileged/update-video-settings`](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/5c37cfa816193f4b487bdec768a08e1b9dfaab10/files/update-video-settings#L57) because the `/opt/tinypilot-updater` directory no longer exists.</s>
    https://github.com/tiny-pilot/ansible-role-tinypilot/issues/206

1. <s>The CircleCI `e2e` step is testing the previous bundle version.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1068

    The `e2e` step basically just [runs `get-tinypilot.sh` and checks if the webserver is returning `HTTP 200`](https://github.com/tiny-pilot/tinypilot/blob/2fd84113cbf3ef57f2f7adf533beff68b7f07b5c/e2e/docker-test#L35-L37). However, the [`e2e` step doesn't wait for the `LATEST` file to be updated](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2384/workflows/7fd79944-6536-4de0-b4b9-c780682948dd) with the newest build version before running because that would effectively "release" the version which makes `e2e` step pointless.

## Test reinstallation on already updated device

Follow these [install instructions](https://gist.github.com/jdeanwallace/f19da96d3efd803fc6bd6a7f78f78b47).

### Bugs

1. <s>TinyPilot Debian package doesn't overwrite on reinstall of the same version **when installing via Ansible**.</s>

    Not really an issue because we're installing the exact same version anyway. However, if we're hacking around on the device and then do a reinstall **via Ansible** it won't "reset to factory settings" because <s>the TinyPilot Debian package</s> **Ansible** skips installation when versions are the same. This is probably ideal seeing as [we don't want to accidentally override settings or configs](https://github.com/tiny-pilot/tinypilot/issues/1027#issue-1282548976).

    However, a dev can overwrite the Debian package files by manually reinstalling the Debian package via:
    
    ```bash
    sudo dpkg --install tinypilot-20220719142135-1-armhf.deb
    ```

    Further reading:    

    * Debian unpack phases: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#details-of-unpack-phase-of-installation-or-upgrade

1. <s>TinyPilot Debian package doesn't remove `__pycache__` directories and `*.pyc` files on uninstall.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1062
    https://github.com/tiny-pilot/tinypilot/pull/1063

    From [Debian packaging manual](https://www.debian.org/doc/packaging-manuals/python-policy/#modules-byte-compilation):
    > The package’s `prerm` has to make sure that both `foo.pyc` and `foo.pyo` are removed.

    Also not much of an issue because `tinypilot` still gets uninstalled successfully with the following warning:
    
    ```bash
    $ sudo apt-get remove tinypilot
    Removing tinypilot (20220711124636) ...
    dpkg: warning: while removing tinypilot, directory '/opt/tinypilot' not empty so not removed
    ```
    
    This leaves a few files & directories inside `/opt/tinypilot`, namely:
    * `venv` directory
    * `app_settings.cfg` file
    * `.pyc` files
    * `__pycache__` directories

    Additionally, the entire [`/opt/tinypilot` directory gets removed by our `preinst` script](https://github.com/tiny-pilot/tinypilot/blob/caecc8fcd3f88ef1003efda6ec3327e543afab91/Dockerfile#L46) anyway.

1. <s>The `/opt/tinypilot-updater` directory ends up with different directory owners (i.e. `pi` or `root`) depending on install vs update.</s>
    https://github.com/tiny-pilot/tinypilot/pull/1074

    When installing:
    ```text
    ++ whoami
    ++ whoami
    + sudo chown pi:pi --recursive /opt/tinypilot-updater
    + pushd /opt/tinypilot-updater
    ```
    
    When updating:
    ```text
    Jul 26 13:30:52 raspberrypi tinypilot-update-svc[698]: ++ whoami
    Jul 26 13:30:52 raspberrypi tinypilot-update-svc[698]: ++ whoami
    Jul 26 13:30:52 raspberrypi tinypilot-update-svc[698]: + sudo chown root:root --recursive /opt/tinypilot-updater
    Jul 26 13:30:52 raspberrypi sudo[781]:     root : TTY=unknown ; PWD=/opt/tinypilot ; USER=root ; COMMAND=/usr/bin/chown root:root --recursive /opt/tinypilot-updater
    Jul 26 13:30:52 raspberrypi sudo[781]: pam_unix(sudo:session): session opened for user root by (uid=0)
    Jul 26 13:30:52 raspberrypi sudo[781]: pam_unix(sudo:session): session closed for user root
    Jul 26 13:30:52 raspberrypi tinypilot-update-svc[698]: + pushd /opt/tinypilot-updater
    ```

    However, this doesn't cause any issues.

## Test downgrade from Pro to Community

Follow these [install instructions](https://gist.github.com/jdeanwallace/dba9fae5aa63b60bd720c172b47264db).

### Bugs

1. <s>Can't read `$FORCE_DOWNGRADE` because the script is being run as root user.</s>
    <s>https://github.com/tiny-pilot/tinypilot/pull/1053</s>
    https://github.com/tiny-pilot/tinypilot/pull/1058

## Test upgrade to Pro on an already updated Community device

Follow these [install instructions](https://gist.github.com/jdeanwallace/2535f964bea25de194f7ae2dd2d1d2d2).

### Bugs

1. <s>Can't git pull Pro repo with non-empty `/opt/tinypilot` directory.</s>
    https://github.com/tiny-pilot/tinypilotkvm.com/pull/769

    Ansible logs:
    ```bash
    TASK [tinypilot.tinypilot-pro : create TinyPilot folder] ***********************
    ok: [localhost]
    
    TASK [tinypilot.tinypilot-pro : get TinyPilot repo] ****************************
    fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin REDACTED", "msg": "fatal: destination path '/opt/tinypilot' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/opt/tinypilot' already exists and is not an empty directory.\n", "stderr_lines": ["fatal: destination path '/opt/tinypilot' already exists and is not an empty directory."], "stdout": "", "stdout_lines": []}
    ```

    Directory contents:
    ```bash
    $ ls -la /opt/tinypilot
    total 52
    drwxr-xr-x  5 tinypilot tinypilot 4096 Jul 26 13:35 .
    drwxr-xr-x  7 root      root      4096 Jul 26 13:30 ..
    -rw-r--r--  1 tinypilot tinypilot   55 Jul 26 13:23 COPYRIGHT
    -rw-r--r--  1 tinypilot tinypilot 1054 Jul 26 13:23 LICENSE
    -rw-r--r--  1 tinypilot tinypilot 7902 Jul 26 13:23 README.md
    -rw-r--r--  1 tinypilot tinypilot    8 Jul 26 13:26 VERSION
    -rw-r--r--  1 tinypilot tinypilot    0 Jul 26 13:23 __init__.py
    drwxr-xr-x 10 tinypilot tinypilot 4096 Jul 26 13:36 app
    -rw-r--r--  1 tinypilot tinypilot  169 Jul 26 13:09 app_settings.cfg
    -rw-r--r--  1 tinypilot tinypilot  404 Jul 26 13:23 requirements.txt
    drwxr-xr-x  2 tinypilot tinypilot 4096 Jul 26 13:35 scripts
    -rw-r--r--  1 tinypilot tinypilot  468 Jul 26 13:23 setup.py
    drwxr-xr-x  6 tinypilot tinypilot 4096 Jul 26 13:35 venv
    ```

### CODE REVIEW

**Comment by mtlynch** [comment]
@jdeanwallace - Yeah a merge from `master` -> `update-overhaul` is fine.

**Comment by jdeanwallace** [comment]
> > The /opt/tinypilot-updater directory is orphaned after an update.
> 
> It's a pretty large directory, so I think we should deal with this now. I filed #1055.

Fixed in https://github.com/tiny-pilot/tinypilot/pull/1060
 
> > We get a HTTP 404 on some local project licenses because the /opt/tinypilot-updater directory no longer exists. Is it still worth referencing these licenses?
> 
> Nice find!
> 
> Yeah, we should fix this. I submitted #1054.

Thanks!

> > TinyPilot Debian package doesn't overwrite on reinstall of the same version.
> 
> This only affects the dev team during testing, right? Is there a workaround where we can just manually remove it before installing a new version?

Sorry actually the "doesn't overwrite on reinstall" part is a feature of when [Ansible installs the Debian package](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/tasks/main.yml#L105-L108). However, if we manually run the following on the device: 
```bash
sudo dpkg --install tinypilot-20220719142135-1-armhf.deb
```
the Debian package files will overwrite the files already on the device. So false alarm.

> > TinyPilot Debian package doesn't remove **pycache** directories and *.pyc files on uninstall.
> 
> Yeah, this seems worth fixing as well. I filed #1056.

Fixed in https://github.com/tiny-pilot/tinypilot/pull/1062 & https://github.com/tiny-pilot/tinypilot/pull/1063

> > Can't read $FORCE_DOWNGRADE because the script is being run as root user.
> 
> Good catch! I think we should fix this, but I'm wondering if there's a cleaner way.

Yes, thanks for your [moving the `sudo` to inside `get-tinypilot.sh` idea](https://github.com/tiny-pilot/tinypilot/pull/1053#pullrequestreview-1037631949). Fixed in https://github.com/tiny-pilot/tinypilot/pull/1058

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1046)

⏳ @mtlynch please review this Pull Request

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1046)

⏳ @jotaen4tinypilot please review this Pull Request

**Comment by jotaen4tinypilot** [comment]
Note to ourselves: don’t forget to revert the branch filter, see https://github.com/tiny-pilot/tinypilot/pull/1087.

**Comment by jotaen4tinypilot** [comment]
Note to ourselves: don’t forget to switch back the ansible version to `master`, https://github.com/tiny-pilot/tinypilot/pull/1088.

**Review by jotaen4tinypilot — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1046)


Approved on CodeApprove
✔️ Approved

To me, it looks like we have everything covered in here.

I have already prepared two draft PRs, so that we don’t forget about the follow-ups after merging.

<hr />

👀 @jdeanwallace, @mtlynch it's your turn please take a look

**Comment by jdeanwallace** [comment]
FYI when it comes to merging this PR the only option available is "Squash and merge", which I assume is okay:
Screen Shot 2022-08-22 at 16 17 59

The reason why we might consider using "Create a merge commit" instead is because the `update-overhaul` branch has been the target branch for multiple PR's and it might be nice to preserve that [merge history](https://github.com/tiny-pilot/tinypilot/commits/update-overhaul) to `master`. However, not a blocker.

**Comment by jotaen4tinypilot** [comment]
I think I’d second the squash-merging, but no strong opinion here either. Due to us merging back `master` a couple of times, the history unfortunately wouldn’t come out as tidy as it could be. (Which is no critique of us merging back `master` frequently!)

Screenshot 2022-08-22 at 16 51 16

(Blue is `master`, red is `update-overhaul`.)

**Pull request merged**
