### PR TITLE
Improve temperature lines in TinyPilot logs

### LINKED ISSUE #1488: Improve temperature lines in TinyPilot logs
The temperature line is currently inconsistent with most other lines in the TinyPilot logs. We should clean it up to be more user-friendly and consistent with our other lines.

### Current

```text
temp=37.0'C
```

### Desired

```text
CPU Temperature: 37.0'C
```

### PR DESCRIPTION
**Pull request by cghague**
Resolves #1488

Runs a simple text replacement to make the output of `vcgencmd measure_temp` more readable.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1542">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1542)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1542)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 135
  vcgencmd measure_temp | sed "s/temp=/CPU Temperature: /g"
```
Seeing as we don't need variable interpolation, can we use single quotes instead of double quotes?


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1542)



<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Resolved

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1542)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
