### PR TITLE
Add e2e test to check for broken license page links

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1136

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1682">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1682)

⏳ @jotaen4tinypilot please review this Pull Request

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1682)



<hr />

In: **Discussion**
Ah, yes that's much simpler. However, I'm reluctant to breakout of the Playwright-way of doing things because then we're not actually testing UI behavior (i.e., click a license link on the about page and open a new tab that doesn't 404).

I don't think I'm able to make this call. Perhaps @mtlynch could share his preference?


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1682)



<hr />

In: **Discussion**
Yeah, I like the `fetch` based solution.

I agree that we should limit how much we bypass Playwright to write our own low-level logic, but [the more Playwright-y version](https://github.com/tiny-pilot/tinypilot/blob/3f884e00dc4df6d53100207a4b107f986dc9fdd0/e2e/about.spec.js#L94-L123) kind of ends up doing that anyway, so we might as well go with the option that performs faster and requires fewer LOC.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1682)



<hr />

In: **Discussion**
> Yeah, I like the fetch based solution.

Sure, done.

@mtlynch - Out of curiosity, in what way does [this version](https://github.com/tiny-pilot/tinypilot/blob/3f884e00dc4df6d53100207a4b107f986dc9fdd0/e2e/about.spec.js#L94-L123) bypass Playwright?


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1682)



<hr />

In: **Discussion**
I guess not really "bypass" Playwright, but it seemed like we were getting stuck hand-coding a lot of logic we needed that wasn't natively available in Playwright. The redirect-checking stuck out to me as us diverging uncomfortably outside of typical Playwright logic. And having to manually override the timeout felt like we were clashing with Playwright a bit, but I don't know of a better way to do it if we have one especially long test.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Pull request merged**
