### PR TITLE
Improve voltage warning lines in TinyPilot logs

### LINKED ISSUE #1495: Improve voltage warning lines in TinyPilot logs
TinyPilot's voltage logs are pretty confusing and inconsistent with the rest of our log file. We should polish them to be easier to understand.

### Current

```
TinyPilot state
Read-only filesystem: off
SSH access: enabled
temp=50.6'C
throttled=0x0

voltage logs <<<

TinyPilot settings.yml
```

#### No warnings case

If we found no voltage issues in the logs, we should just say that there are no voltage issues:

```text
Voltage issues: No
```

#### Warnings case

If we detect an issue in the logs related to voltage, we should say "Yes" and print the last log message related to voltage. It should just be one log line, as we've never needed more than that.

```text
Voltage issues: Yes - Jun 05 03:48:29 tinypilot kernel: Under-voltage detected! (0x00050005)
```

### PR DESCRIPTION
**Pull request by cghague**
Resolves #1495

Parses the output of `journalctl` into a simple “yes” or “no” result. If the result is “yes”, the latest voltage warning is also included in the output.

## Parsing the output of `journalctl`

I initially considered piping the output of `journalctl` into `grep` for readability, but getting the correct exit code as well as just the latest voltage warning was quite awkward with this approach. I therefore settled on using just the filtering and output options that are built into `journalctl`:

- The `-q` argument is used to suppress the unwanted `journalctl` header text.
- The `-r` argument causes `journalctl` to output from newest to oldest.
- The `-n 1` argument causes `journalctl` to stop after outputting a single line.
- The `-g "voltage"` argument limits output to only lines that contain the word “voltage”.

The end result of this combination of arguments is that `journalctl` will efficiently output only the most recent voltage warning. In addition, the exit status of the command reflects whether or not any matching lines were found, which allows for a simple `if <command>` test to be used.

Short arguments were used for consistency with the majority of the rest of the `collect-debug-logs` script.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1544">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1544)

⏳ @jdeanwallace please review this Pull Request

**Comment by mtlynch** [comment]
@cghague - Just a heads up that I'm reassigning these reviews to @jdeanwallace since I'm backed up this week.

**Review by jdeanwallace — DISMISSED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1544)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM!

<hr />

In: **Discussion**
> Short arguments were used for consistency with the majority of the rest of the collect-debug-logs script.

I think this is generally the right choice, but in this case there is already a few other instances of using the prefered long arguments ([1](https://github.com/tiny-pilot/tinypilot/blob/52365c393ff4c5515ec427ecd2bb028b30c16aa6/debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs#L79-L80), [2](https://github.com/tiny-pilot/tinypilot/blob/52365c393ff4c5515ec427ecd2bb028b30c16aa6/debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs#L181), [3](https://github.com/tiny-pilot/tinypilot/blob/52365c393ff4c5515ec427ecd2bb028b30c16aa6/debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs#L223)) that I think we should just go with using long arguments in this PR.

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 142
  if LAST_VOLTAGE_LINE=$(journalctl -q -r -n 1 -g "voltage") ; then
```
Can we quote the command substitution?

From [Google Shell style guide](https://google.github.io/styleguide/shellguide.html#quoting):
> ```bash
> # "quote command substitutions"
> # Note that quotes nested inside "$()" don't need escaping.
> flag="$(some_command and its args "$@" 'quoted separately')"
> ```


<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:

```
> Line 145
    printf "No"
```
This is [something new I just confirmed with Michael](https://github.com/tiny-pilot/tinypilot/issues/1489#issuecomment-1662489808), but can we use a lowercase "yes"/"no"?


<hr />

👀 @cghague it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1544)



<hr />

In: **Discussion**
+1

If we have a defined convention, we usually want to use that one. If a file is internally consistent in violating our convention, and it would look weird to use our official convention (e.g., spaces in a file that consistently uses tabs), then we should be locally consistent.

But for cases where the file itself is inconsistent in adhering to a convention, we should go with our style guide.

I've filed https://github.com/tiny-pilot/tinypilot/issues/1547 to make `collect-debug-logs` consistent.


<hr />

👀 @cghague, @jdeanwallace it's your turn please take a look

**Review by cghague — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1544)



<hr />

In: **Discussion**
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Resolved

<hr />

In: **debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs**:
Resolved

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1544)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
