### PR TITLE
Video Settings dialog: clean up / simplify component implementation

### LINKED ISSUE #1108: Video settings dialog spins infinitely on error
I ran into an error where the `POST` to `/api/settings/video/apply` failed, which caused the video settings dialog to spin forever:

image

It looks like the problem is here:

https://github.com/tiny-pilot/tinypilot/blob/6073998459e21317800139df38166cd34396d4fd/app/templates/custom-elements/video-settings-dialog.html#L316

We assume that `applyVideoSettings` can't fail because saving the individual fps or jpeg quality settings didn't fail, but we missed that we can still fail on the last part (kicking off the Ansible job to apply uStreamer settings).

### PR DESCRIPTION
**Pull request by jotaen4tinypilot**
Part of https://github.com/tiny-pilot/tinypilot/issues/1112.

This is a non-functional refactoring of the component’s JS implementation, which should help to extend the class with the upcoming functionality.

These are my thoughts behind the changes. Please don’t be scared by the amount of text, it’s (hopefully) all not as complicated as it might seem at first glance 🙈 … I thought it makes more sense to do this all in one collective PR, because many of the changes are related, and we also only need one round of QA’ing.

- I renamed `getSettings` to `initialize`. We are [not consistent with naming these entrypoint methods](https://github.com/tiny-pilot/tinypilot/blob/6073998459e21317800139df38166cd34396d4fd/app/static/js/app.js#L322-L353), but at least `initialize()` appears twice. I think it makes sense to have a uniform method name here, as the function is basically like the “constructor” of the dialog.
- I dropped all `video` prefixes from both the CSS and JS code. I think they create a lot of noise, and to me the purpose of the identifiers is sufficiently clear from the context.
- I’ve added `this.elements`, to avoid repeating CSS identifiers.
- I prefixed `this.defaultSettings` with an `_`, [according to our recently updated coding conventions](https://github.com/tiny-pilot/tinypilot/blob/6073998459e21317800139df38166cd34396d4fd/CONTRIBUTING.md?plain=1#L236-L238). Note that `this.elements` is [still an explicit exception](https://github.com/tiny-pilot/tinypilot/blob/6073998459e21317800139df38166cd34396d4fd/CONTRIBUTING.md?plain=1#L216). I’ve opened https://github.com/tiny-pilot/tinypilot/issues/1120 for tracking this inconsistency.
- I’ve simplified fetching and saving, because those two operations always happen for *all* settings. So I think the benefit of having individual methods (like `_fetchVideoFps()`) is not worth the amount of code that takes. One by-effect of this is that the error messages are not as fine-granular anymore, so if something fails it just says: “Failed to Change Video Settings” instead of “Failed to Save Video FPS”. To me, that’s okay, since this doesn’t make a practical difference for the end-user, and for debugging we can tell from the logs which one API request caused the failure.
- I’ve made the internal typing of the settings values more rigorous, since we mixed `number` and `string` throughout the code. E.g., the API returns a `30` (number) for the default JPEG quality, but when reading the current value from the slider element or the change event, we get a string `"30"` (string). This didn’t cause any troubles yet, because both JS and Python took care of the type conversion by itself – we actually even sent a string to the server in the JSON request body. Anyway: the type ambiguity might be confusing, and I also already noticed that strict typing [will become relevant when implementing the auto-disabled “Apply” button](https://github.com/tiny-pilot/tinypilot-pro/pull/598/files#diff-58e8fc422e36f9a87c5e645b8eab3c0dc660f3b7173978fbaf2289c60f0b99ebR272) (so that we can compare via `===` instead of `==`).
- `_setFps` (formerly `_setVideoFpsDisplay`) et al previously only set the value next to the slider. I think it makes more sense, though, to also adjust the slider value, to make the change atomic and to prevent potential inconsistency bugs. That means, that when `_setFps` is invoked from the slider element event handler, we effectively re-set the slider value down the line. That’s not very useful per se, of course, but I still think the `_setFps` implementation is more robust that way. Note, setting the `.value` property on an input element doesn’t re-trigger the `"change"` event handler, so we are safe in regards to an endless update loop.
- I’ve then also added matching `_get...` methods for the settings, just to separate and group the concerns a bit better.
- We previously [swallowed errors emitted by `applyVideoSettings`](https://github.com/tiny-pilot/tinypilot/compare/video-settings/refactor-js?expand=1#diff-58e8fc422e36f9a87c5e645b8eab3c0dc660f3b7173978fbaf2289c60f0b99ebL308), because the subsequent `catch` handler was empty. This is fixed now.

Fixes #1108

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1121">Review on CodeApprove</a>

### CODE REVIEW

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1121)


Approved on CodeApprove
✔️ Approved (1 unresolved comments)

Nice, very clean implementation. LGTM!

<hr />

In: **app/templates/custom-elements/video-settings-dialog.html**:

```
> Line 121
            buttonRestore: this.shadowRoot.querySelector("#edit .restore-btn"),
```
(nit) Can we rename these elements to match the class names. For example: `saveButton`, `closeButton`.

<hr />

In: **app/templates/custom-elements/video-settings-dialog.html**:

```
> Line 141
            this._setFps(parseInt(event.target.value, 10));
```
Interesting to learn about [`parseInt`'s `radix` parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#parameters).


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Comment by mtlynch** [comment]
>We previously [swallowed errors emitted by applyVideoSettings](https://github.com/tiny-pilot/tinypilot/compare/video-settings/refactor-js?expand=1#diff-58e8fc422e36f9a87c5e645b8eab3c0dc660f3b7173978fbaf2289c60f0b99ebL308), because the subsequent catch handler was empty. This is fixed now.

Cool, this fixes #1108. I've linked this PR to the bug.

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1121)



<hr />

In: **Discussion**
We should just merge this one because @jdeanwallace already reviewed it, but this is a bit high-complexity for a refactoring change. In the future, I'd like to do changes like these in smaller, more narrowly scoped PRs. A lot of these changes would work better as independent/stacked PRs (e.g., rename a function should be its own PR).

We're also [mixing functional and non-functional changes](https://mtlynch.io/code-review-love/#6-separate-functional-and-non-functional-changes), which I'd especially like to avoid. We're changing error messages and changing behavior on #1108.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

**Review by jotaen4tinypilot — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1121)



<hr />

In: **Discussion**
Yeah, I agree that this went a bit out of hand.

<hr />

In: **app/templates/custom-elements/video-settings-dialog.html**:
Done!

<hr />

In: **app/templates/custom-elements/video-settings-dialog.html**:

```
> Line 143
            this._setFps(parseInt(event.target.value, 10));
```
There is a funny code puzzle around it (in case you don’t know it):

```js
["1", "5", "10", "20"].map(parseInt)
```

You could think this returns

```js
[1, 5, 10, 20]
```

But instead, it gives you:

```js
[1, NaN, 2, 6]
```

Reason is that [`Array.map` passes the array index](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) as second parameter to the callback function, which `parseInt` then interprets as the radix.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1121)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Comment by jotaen4tinypilot** [comment]
> Cool, this fixes https://github.com/tiny-pilot/tinypilot/issues/1108. I've linked this PR to the bug.

Oh, nice timing 😄

**Pull request merged**
