### PR TITLE
Direct users to the Network Status dialog

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1826

This PR adds a convenience button that opens the Network Status dialog after a user configures their Wi-Fi credentials.

Additionally, we've added a hint to the tooltip of the `<connection-indicator>` to direct users to the Network Status dialog.

Demo video:

https://github.com/user-attachments/assets/210fe26e-4e03-475f-9e99-f0e21d75cc20

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1831">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1831)

⏳ @db39 please review this Pull Request

**Comment by jdeanwallace** [comment]
@db39 - Just checking if this is still on your radar?

**Comment by jdeanwallace** [comment]
@db39 - Just checking if this is still on your radar?

**Comment by db39** [comment]
@jdeanwallace - Sorry, I completely missed this, I'm not sure why I didn't get the notifications before. Thanks for the ping.

**Review by db39 — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1831)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1831">Approved on CodeApprove</a>
✔️ Approved

LGTM!

<hr />

👀 @jdeanwallace it's your turn please take a look

**Pull request merged**
