### PR TITLE
Add a Privacy Policy to About page

### PR DESCRIPTION
**Pull request by mtlynch**
Add a privacy policy to cover the types of data we collect from TinyPilot and link to it from the About page.

We don't collect OS and software version in the Community version yet, but we've included language for it in the privacy policy in case we decide to collect that in the future.

TinyPilot Pro will have adjustments to this policy, as it collects additional information for license checking.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1096">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1096)

⏳ @jdeanwallace please review this Pull Request

**Comment by mtlynch** [comment]
@jdeanwallace - You don't have to review the legal stuff, just the code part.

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1096)


Approved on CodeApprove
✔️ Approved (1 unresolved comments)

LGTM!

<hr />

In: **app/find_files/find.py**:

```
> Line 9
        ('./app/static/legal', '*'),
```
Should we lock this down to only the `.txt` extensions for now?

Also if we want nginx to serve `privacy-policy.txt` as a static file we'll need to add a specific file extension to our [nginx config](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/b29d65e32ddd1f613edb2bd33249dfc16d642933/tasks/nginx.yml#L86-L88). 
Side note: It seems like our nginx config still serves `.svg` files via Flask.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1096)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
