### PR TITLE
add 64bit warning

### PR DESCRIPTION
**Pull request by yamato225**
#929

---
This change is [Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/930)

### CODE REVIEW

**Comment by mtlynch** [comment]
@jdeanwallace - Can you take this review?

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
@yamato225 Thanks for adding this!

I've made a few comments, mostly about code style. We try to follow the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html) as best as we can.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-:-MxmjTFE5GMXvE1pl-p0:b-91tckv)* status: 0 of 1 LGTMs obtained

___
*[quick-install, line 38 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-Mxmi1cd2rAxvhh2aqrL:-Mxmi1cd2rAxvhh2aqrM:b-m2o0nh) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/f2962011bc12b1eba1725f6cc78f6e98fccc36c2/quick-install#L38)):*
> ```
> set -u
> 
> # Stop installation on 64bit OS(temporary, this step will remove)
> ```

Can we reword this comment to make it clearer?

Something like:
```bash
# Prevent installation on the 64bit version of Raspberry Pi OS.
# TODO: Add support for 64bit Raspberry Pi OS.
```
___
*[quick-install, line 39 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-MxmbEyE81u9PtbDNgcn:-MxmbEyE81u9PtbDNgco:bxrn3uf) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/f2962011bc12b1eba1725f6cc78f6e98fccc36c2/quick-install#L39)):*
Can we quote this shell command substitution (i.e. `"$(...)"`)?

From the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html#quoting):
> ```bash
> # "quote command substitutions"
> # Note that quotes nested inside "$()" don't need escaping.
> flag="$(some_command and its args "$@" 'quoted separately')"
> ```

So that we end up with something like:
```bash
if [[ "$(uname -m)" == 'aarch64' ]]; then
  ...
```
___
*[quick-install, line 40 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-Mxm_dUeAOG17E7w4TtH:-Mxm_dUeAOG17E7w4TtI:bevju4l) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/f2962011bc12b1eba1725f6cc78f6e98fccc36c2/quick-install#L40)):*
Can we use a 2-space indentation here?

From the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html#indentation):
> Indent 2 spaces. No tabs.
___
*[quick-install, line 40 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-MxmeP_D3Wy1eWujf3oX:-MxmeP_EDX2rsUd5dDfK:bnzd068) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/f2962011bc12b1eba1725f6cc78f6e98fccc36c2/quick-install#L40)):*
> ```
> # Stop installation on 64bit OS(temporary, this step will remove)
> if [[ $(uname -m) == 'aarch64' ]];then
>     echo "Warning: currently tinypilot doesn't support on 64bit OS. Use 32bit." >&2
> ```

I would only classify this as a warning if the installation continued. In this case, the installation stops completely.

To keep with the style of the rest of the file, can we change the error message to something this?
```bash
echo '64bit Raspberry Pi OS is not yet supported.' >&2
echo 'Please use the 32bit version of Raspberry Pi OS.' >&2
exit 1
```

**Comment by yamato225** [comment]
Thank you for your comment, and nice review.
I have fixed these as you said.

**Review by jdeanwallace — APPROVED** [review]
Thanks @yamato225! Just one last small change then we're ready to merge.

:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-:-My6K2IC29VaL0blgnuu:b-yspuxr)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[quick-install, line 40 at r2](https://reviewable.io/reviews/tiny-pilot/tinypilot/930#-My6JLwp9X8oSXuQYM0X:-My6JLwp9X8oSXuQYM0Y:by7llnj) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/19cae6fe06740886ee8e7908ad126201521b9b34/quick-install#L40)):*
> ```
> # Prevent installation on the 64bit version of Raspberry Pi OS.
> # TODO: Add support for 64bit Raspberry Pi OS.
> if [[ "$(uname -m)" == 'aarch64' ]];then
> ```

(nitpick) Can we add a space between the `;` and `then`?

So that we end up with:

```bash
if [[ "$(uname -m)" == 'aarch64' ]]; then
```

**Pull request merged**
