### PR TITLE
Consolidate the ansible-role-ustreamer repo into the TinyPilot repo

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/tinypilot/issues/1426
Blocked on https://github.com/tiny-pilot/ansible-role-ustreamer/issues/113

This PR is an exact copy of the [`ansible-role-ustreamer` repo](https://github.com/tiny-pilot/ansible-role-ustreamer/tree/02f37b869c8c585517a9c7b6cd95cfb7661f1490) into the `ansible-role-ustreamer/` directory.

The CI checks are resolved in subsequent PRs:
* https://github.com/tiny-pilot/tinypilot/pull/1435
* https://github.com/tiny-pilot/tinypilot/pull/1436

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1434">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1434)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1434)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1434">Approved on CodeApprove</a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by jdeanwallace** [comment]
@mtlynch - Oh yes, these PRs are blocked on https://github.com/tiny-pilot/ansible-role-ustreamer/issues/113. Once [we archive the `ansible-role-ustreamer` repo](https://github.com/tiny-pilot/ansible-role-ustreamer/issues/113#issuecomment-1593068301), we can merge these PRs.

**Comment by mtlynch** [comment]
Ah, I was waiting to archive it until we completed the move. I figured that until we'd moved it, then there was a small chance we'd want to change something in the source repo.

But it's archived now, so we should be unblocked.

**Pull request merged**
