### PR TITLE
Mark uStreamer interface and port as constant system settings

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/tinypilot/issues/1429

This PR removes the implication that `ustreamer_interface` and `ustreamer_port` could be user-configurable. They are instead considered TinyPilot constants that should not be overridden by `/home/tinypilot/settings.yml`.

Notes
1. This PR was triggered based on [our discussion](https://codeapprove.com/pr/tiny-pilot/tinypilot/1469#thread-03723286-15ac-4bb6-b466-86223f9b94c0) about user-configurable variables.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1493">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
@mtlynch - FYI, I just made some last minute changes to the PR description.

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM modulo the `tinypilot_` vars

<hr />

In: **ansible-role/vars/main.yml**:

```
> Line 11
tinypilot_interface: "127.0.0.1"
```
Can we limit this PR to the uStreamer changes?

If we're touching `tinypilot_interface` and `tinypilot_port`, we should just be deleting them (in a separate PR) because we're close to deleting them anyway:

https://github.com/tiny-pilot/tinypilot-pro/issues/972


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)


❌ Undo Approval (1 unresolved comments)

Wait, thinking about this more, won't this cause us to write the default `ustreamer_interface` and `ustreamer_port` values into `settings.yml`?

<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)



<hr />

In: **Discussion**
Sorry, I think I understand now. This wouldn't cause us to overwrite `settings.yml` with the default value.

You're saying we'd make a Pro-only change to hardcode `ustreamer_interface` and `ustreamer_port`?

Hardcoding `ustreamer_interface` is fine because it's just `localhost` and we should never have made vars for it in the first place.

I don't want to hardcode `ustreamer_port` in one place but use the var in other places because then it's too easy for the two to go out of sync.

Could we put `ustreamer_port`in a separate `dict` called `_CONSTANTS` to make it obvious that it's not user-configurable but we otherwise preserve the existing functionality? `_CONSTANTS` should override anything in `_DEFAULTS` and in the `settings.yml` file.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **app/update/settings_test.py**:

```
> Line 88
        # `8001` happens to be the constant ustreamer_port value.
```
"happens to be" kind of sounds like it's accidental. Suggest:

```python
# Verify that the constant value of ustreamer_port took precedence over the value in the settings file.
```

<hr />

In: **app/update/settings.py**:

```
> Line 64
        # highest precedence.
```
Suggest rephrasing to make it obvious how all three relate to each other.

```python
# Merge the defaults with the data and constants. In case of conflicting keys, the precedence is:
# 1. Constants (highest precedence)
# 2. Data
# 3. Defaults (lowest precedence)
```

<hr />

In: **app/update/settings.py**:

```
> Line 132
    """Writes a Settings object to a file, excluding any constants or defaults.
```
Suggest:

```python
"""Writes a Settings object to a file, excluding constants and defaults."""
```

Just so it fits on a single line.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)



<hr />

In: **app/update/settings_test.py**:
Thanks, done.

<hr />

In: **app/update/settings.py**:
Thanks, done.

<hr />

In: **app/update/settings.py**:
Thanks, done.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1493)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
