### PR TITLE
Update README with more specific requirements

### LINKED ISSUE #1855: Update README to be more specific with OS requirements
Our README lists Raspberry Pi OS Bullseye (32-bit) as a pre-requisite for installing TinyPilot, but it still trips people up.

We should update our README to be more clear about the requirements here.

### PR DESCRIPTION
**Pull request by db39**
Resolves #1855

This change updates our README to be more clear with installation requirements. The "pre-requisites" section is now a "requirements" under the "Simple installation" heading.

This change also removes the Reddit link shield that links to the unused TinyPilot subreddit.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1856">Review on CodeApprove</a>

### CODE REVIEW

**Comment by db39** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)

⏳ @cghague please review this Pull Request

**Review by cghague — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM

<hr />

In: **README.md**:

```
> Line 57
- A Raspberry Pi 4 running Raspberry Pi OS Bullseye (32-bit)
```
Nit: It should be Raspberry Pi 4 **B**.


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)



<hr />

In: **README.md**:

```
> Line 57
- A Raspberry Pi 4 running Raspberry Pi OS Bullseye (32-bit)
```
Our "Build your own" section says [Raspberry Pi 4 (all variants work)](https://github.com/tiny-pilot/tinypilot/blob/master/README.md?plain=1#L37), so I stayed consistent with that.

I'm unsure whether "all variants" refers to variants of the 4B (it's slightly confusing because we link to an Amazon listing for a 4B), or the Pi 4 in general. I don't mind removing the mention of all variants so that we specifically ask people to use a 4B.


<hr />

👀 @cghague it's your turn please take a look

**Review by cghague — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **README.md**:

```
> Line 57
- A Raspberry Pi 4 running Raspberry Pi OS Bullseye (32-bit)
```
"Variants" likely refers to the different Raspberry Pi 4B storage capacities, as TinyPilot should work on all of them. For clarity, I suggest changing all mentions of the model to `Raspberry Pi 4B` and replacing the word `variants` with `capacities`.


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)



<hr />

In: **README.md**:
Thanks! I've updated to use 4B in both places. I removed the mention of "all variants work" because I think that wording can just cause added confusion. I think saying "Raspberry Pi 4B" covers its different RAM options.

**Review by cghague — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1856)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
