### PR TITLE
Populate TC358743 EDID file without Ansible

### PR DESCRIPTION
**Pull request by mtlynch**
Related #1598

In continuing our elimination of Ansible, this reimplements the logic to populate the TC358743 EDID file (at `/home/ustreamer/edids/tc358743-edid.hex`) without Ansible.

We preserve the existing behavior that if the user has overridden the desired EDID by specifying a different value for `ustreamer_edid`, then we use that value when we populate `/home/ustreamer/edids/tc358743-edid.hex` on the next install.

The output of our `decode_edid` step changes because we're using a different version of the Docker image which seems to pull down a different version of the `decode-edid` which uses slightly different output formatting, but the values are all the same.

I was originally bundling this with #1604, but that PR is pretty large since it eliminates Ansible entirely, so I'm pulling out a small piece here.

## Peer testing

To test this bundle run:

```bash
curl \
  --silent \
  --show-error \
  --location \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/scripts/install-bundle | \
  sudo bash -s -- \
    https://output.circle-artifacts.com/output/job/4a10bf35-34f1-4924-8af3-52f3dea7217a/artifacts/0/bundler/dist/tinypilot-community-20230901T1402Z-1.9.0-77+4903bc6.tgz
```

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1616">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)



<hr />

In: **Discussion**
Can we inline the value of `ustreamer_edids_dir` here?
https://github.com/tiny-pilot/tinypilot/blob/4903bc662a38e2990d9ec6ebfbf53344a9cd38f8/ansible-role-ustreamer/templates/load-tc358743-edid.systemd.j2#L12

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 111
  mkdir -p /home/ustreamer/edids/
```
(nit) Can we drop the trailing `/`?

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 117
    > /home/ustreamer/edids/tc358743-edid.hex && \
```
Can we ensure that the file permissions are also set to `0644`?


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)



<hr />

In: **Discussion**
Whoops, yes we need to. Forgot we'd need to do that since in the other PR that file is gone entirely.

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
Sure, fixed

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 117
    > /home/ustreamer/edids/tc358743-edid.hex && \
```
Good idea! Fixed.


<hr />

👀 @jdeanwallace it's your turn please take a look

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

Tested on a TinyPilot voyager device 👍

<hr />

In: **debian-pkg/debian/tinypilot.postinst**:

```
> Line 119
    chmod 0644 /home/ustreamer/edids/tc358743-edid.hex
```
Can we fix the indentation here?


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)



<hr />

In: **debian-pkg/debian/tinypilot.postinst**:
Sure, fixed.

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1616)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
